import test from 'node:test';
import assert from 'node:assert/strict';
import {rewardRegistry,rewardLimit,giftBudget,gifts,emptyPetState,awardPoints,earnedPoints,balance,buyGift,giveGift,normalizePetState} from '../pets.js';
const ids=['orbit','signal','pairs','traffic','sort','search','route','robot','reverse','cargo','tracking','hanoi','puzzle','pattern','wait','chain'],registry=rewardRegistry(ids);
test('27个奖励任务共270分，9件礼物总价270，新增游戏自动增加预算',()=>{assert.equal(Object.keys(registry).length,27);assert.equal(rewardLimit(registry),270);assert.equal(gifts.length,9);assert.equal(giftBudget(),270);assert.equal(rewardLimit(rewardRegistry([...ids,'new-game'])),280);});
test('短回合5、完整累计10、重复/未知任务不发分，机器人关卡独立',()=>{let s=emptyPetState();s=awardPoints(s,registry,{id:'orbit',trial:true}).state;assert.equal(balance(s),5);s=awardPoints(s,registry,{id:'orbit',trial:false}).state;assert.equal(balance(s),10);assert.equal(awardPoints(s,registry,{id:'orbit',trial:true}).added,0);assert.equal(awardPoints(s,registry,{id:'missing'}).added,0);assert.equal(awardPoints(s,registry,{id:'robot',level:13}).added,0);for(const level of [1,2])s=awardPoints(s,registry,{id:'robot',level,trial:false}).state;assert.equal(balance(s),30);});
test('所有任务足够兑换全部礼物，不能负余额或重复购买',()=>{let s=emptyPetState();assert.ok(buyGift(s,gifts[0].id).error);for(const id of ids){for(const level of id==='robot'?Array.from({length:12},(_,i)=>i+1):[1])s=awardPoints(s,registry,{id,level,trial:false}).state;}assert.equal(earnedPoints(s),270);for(const g of gifts){const result=buyGift(s,g.id);assert.equal(result.error,null);s=result.state;}assert.equal(balance(s),0);assert.equal(s.purchases.length,9);assert.ok(buyGift(s,gifts[0].id).error);assert.equal(balance(s),0);});
test('未兑换不能使用，换猫狗分别保留打扮，零食反复使用不扣分',()=>{let s=emptyPetState();s=awardPoints(s,registry,{id:'orbit',trial:false}).state;s=awardPoints(s,registry,{id:'signal',trial:false}).state;s.selected='cat';assert.ok(giveGift(s,'star-hat').error);s=buyGift(s,'star-hat').state;s=giveGift(s,'star-hat').state;assert.equal(s.pets.cat.hat,'star-hat');s.selected='dog';assert.equal(s.pets.dog.hat,null);s=giveGift(s,'star-hat').state;assert.equal(s.pets.cat.hat,s.pets.dog.hat);s=awardPoints(s,registry,{id:'search',trial:false}).state;s=buyGift(s,'star-snack').state;for(let i=0;i<3;i++)s=giveGift(s,'star-snack').state;assert.equal(balance(s),0);assert.equal(s.purchases.length,2);assert.equal(normalizePetState(JSON.parse(JSON.stringify(s)),registry).pets.dog.hat,'star-hat');});
test('损坏存档被过滤，已兑换不超过累计积分，装备只能引用已拥有礼物',()=>{const s=normalizePetState({version:1,credits:{orbit:10,signal:-5,pairs:Infinity,robot:1000},purchases:[{id:'star-hat',paid:20},{id:'star-snack',paid:10},{id:'star-snack',paid:10}],selected:'cat',pets:{cat:{hat:'star-hat',snack:'star-snack'}}},registry);assert.equal(balance(s),0);assert.equal(s.purchases.length,1);assert.equal(s.pets.cat.hat,null);assert.equal(s.pets.cat.snack,'star-snack');});
