import {createJourney} from './journey.js';
import {robotLevel,solveRobot} from './upgrades.js';
import {folders,gameArtwork} from './library.js';
import {extraGames,createBatch2} from './batch2.js';
import {shuffle,numbers,orbitLayout,robotStep,tickClock} from './logic.js';

const app=document.querySelector('#app');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const icons=['🪐','🌙','☀️','⭐','🚀','🛰️','☄️','🔋'];
const palettes=['#ffcc76','#a1b5ff','#74dbcf','#f5a4bb','#baabf5','#83cce9','#ffd785','#b5dc95'];
const games=[
  {id:'orbit',name:'数字轨道',tag:'顺序搜索',icon:'01',color:0,description:'在旋转的星系里，按顺序找到数字。',instruction:'从 1 开始，按顺序点数字。点对后它会留在原处，变成已完成。',example:'先找 1，再找 2，最后找 3。',symbol:'🪐'},
  {id:'signal',name:'星球信号',tag:'序列记忆',icon:'02',color:1,description:'看星球亮起，再把信号重复一遍。',instruction:'先看星球亮起的顺序。看到「轮到你啦」后，按同样顺序点击。',example:'如果月亮、星星依次亮起，就先点月亮，再点星星。',symbol:'🌙'},
  {id:'pairs',name:'太空配对',tag:'位置记忆',icon:'03',color:2,description:'翻开太空卡片，找到一样的伙伴。',instruction:'每次翻两张卡片。一样就配对成功，不一样就记住它们的位置，再试一次。',example:'翻到两张火箭，就找到一对啦。进阶版配对后，其他卡片会缓慢换位置。',symbol:'🛰️'},
  {id:'traffic',name:'飞船通行灯',tag:'等待行动',icon:'04',color:3,description:'等通行信号，再让飞船出发。',instruction:'看到 ✓ 通行就点击发射；看到 ✋ 等待就先不动。每次信号只需要点击一次。',example:'✓ 通行：发射！✋ 等待：让飞船停好。',symbol:'🚀'},
  {id:'sort',name:'星际分拣站',tag:'规则切换',icon:'05',color:4,description:'看看现在的规则，送物品回家。',instruction:'看上方规则，将物品送进正确的分类箱。先按颜色；进阶版中途会切换为按形状。',example:'按颜色时，蓝色三角形也要进蓝色箱；按形状时，它要进三角形箱。',symbol:'🔷'},
  {id:'search',name:'陨石找目标',tag:'寻找目标',icon:'06',color:5,description:'在漂浮的陨石里，发现特别的一颗。',instruction:'看清目标的颜色和形状，再从场景里点出完全相同的一颗。',example:'目标是蓝色三角形，蓝色圆形和橙色三角形都不符合。',symbol:'☄️'},
  {id:'route',name:'航线记忆',tag:'空间记忆',icon:'07',color:6,description:'记住飞船走过的星球，重走航线。',instruction:'先看飞船访问星球的顺序。航线消失后，按原顺序点击星球。',example:'飞船先到左边，再到右边，你也按这个顺序点击。',symbol:'⭐'},
  {id:'robot',name:'机器人指令',tag:'规划路线',icon:'08',color:7,description:'排好指令，带机器人抵达空间站。',instruction:'用「前进、左转、右转」排一段指令，再点执行。转向只改变方向，不会移动。',example:'例如机器人面朝右，左转后就朝上；再点前进，就向上走一格。',symbol:'🤖'}
];
games.push(...extraGames);
let settings={schemaVersion:1,difficulty:'easy',motion:reduced.matches?'still':'slow',sound:false,count:10};
try {const saved=JSON.parse(localStorage.getItem('star-team-settings'));if(saved?.schemaVersion===1){for(const [key,options]of Object.entries({difficulty:['easy','challenge'],motion:['still','slow','normal'],count:[10,20,30,50]})){if(options.includes(saved[key]))settings[key]=saved[key];}if(typeof saved.sound==='boolean')settings.sound=saved.sound;}}catch{}
if(reduced.matches)settings.motion='still';
let activeFolder=null;
let selected=null,view='home',session=null,message='',audioContext=null,last=performance.now();
const batch2=createBatch2({session:()=>session,settings:()=>settings,render:()=>renderPlay(),finish:()=>finish(),feedback:(text,bad)=>feedback(text,bad),setMessage:text=>{message=text;}});
const optionSpecs={level:Array.from({length:12},(_,i)=>i+1),memoryCount:[0,2,3,4,5],playback:[1.05,1.5,2],observation:[0,6,10,15],trackingCount:[4,6,8],trackingTargets:[1,2,3],chainPairs:[1,2,3]};
let profiles={};try{const stored=JSON.parse(localStorage.getItem('star-team-profiles'));for(const g of games){const clean={};for(const [key,values] of Object.entries(optionSpecs))if(values.includes(stored?.[g.id]?.[key]))clean[key]=stored[g.id][key];profiles[g.id]=clean;}}catch{}
function optionsFor(id){return {memoryCount:0,playback:1.05,observation:0,trackingCount:settings.difficulty==='challenge'?6:4,trackingTargets:settings.difficulty==='challenge'?2:1,chainPairs:settings.difficulty==='challenge'?2:1,level:settings.difficulty==='challenge'?7:1,...profiles[id]};}
function saveProfiles(){try{localStorage.setItem('star-team-profiles',JSON.stringify(profiles));}catch{}}
function extraSettings(g){const keys=g.id==='robot'?['level']:g.id==='signal'||g.id==='route'?['memoryCount','playback']:g.id==='cargo'?['memoryCount','observation']:g.id==='tracking'?['trackingCount','trackingTargets','observation']:g.id==='chain'?['chainPairs','observation']:[];
 const labels={level:'机器人关卡',memoryCount:'起始记忆数量',playback:'每个信号的播放时间',observation:'看清单 / 目标的时间',trackingCount:'卫星总数',trackingTargets:'需要跟住的目标',chainPairs:'取物送达任务数'},opts=optionsFor(g.id);
 return keys.length?'<div class="settings extra-settings">'+keys.map(key=>'<label>'+labels[key]+'<select data-option="'+key+'">'+optionSpecs[key].map(v=>'<option value="'+v+'" '+(opts[key]===v?'selected':'')+'>'+ (key==='level'?'第 '+v+' 关':key==='observation'?(v===0?'等我点「记住了」':v+' 秒'):key==='playback'?v+' 秒':v===0?'随难度调整':v+(key==='chainPairs'?' 组 · '+v*2+' 步':' 个'))+'</option>').join('')+'</select></label>').join('')+'</div><p class="micro">这些设置会记住，下次可以接着探索。</p>':'';
}
const journey=createJourney({games,home:()=>renderHome(),show:content=>{view='journey';session=null;message='';shell(content);app.querySelector('main h1')?.focus({preventScroll:true});},prepare:id=>{selected=games.find(g=>g.id===id);activeFolder=folders.find(f=>f.games.includes(id));renderReady();},snapshot:()=>session?{session,settings:{...settings},message}:null,restore:saved=>{selected=games.find(g=>g.id===saved.session.id);activeFolder=folders.find(f=>f.games.includes(selected.id));settings={...settings,...saved.settings};if(reduced.matches)settings.motion='still';session=saved.session;session.paused=true;view='demo';message=saved.message;last=performance.now();renderPlay();app.querySelector('[data-action="resume"]')?.focus();}});
function saveSettings(){try{localStorage.setItem('star-team-settings',JSON.stringify(settings));}catch{}}
function heroArt(){return `<svg viewBox="0 0 400 290" role="img" aria-label="飞船绕着星球探索"><ellipse cx="210" cy="148" rx="165" ry="92" fill="none" stroke="#6c83b6" stroke-opacity=".3" stroke-dasharray="5 9" transform="rotate(-16 210 148)"/><circle cx="211" cy="144" r="75" fill="#a6b5f5"/><path d="M141 120q70-34 140 5M139 151q70-25 145 12M154 186q65-16 112 11" stroke="#6d7dc2" stroke-width="15" fill="none" opacity=".42"/><ellipse cx="211" cy="149" rx="125" ry="28" fill="none" stroke="#ffd28c" stroke-width="14" transform="rotate(-22 211 149)"/><g transform="translate(290 43) rotate(35)"><path d="M0 40Q-10 8 15-21Q40 8 30 40Z" fill="#eef4fc"/><circle cx="15" cy="7" r="9" fill="#63c8d4"/><path d="M0 22l-15 20 15-2M30 22l15 20-15-2" fill="#f6aa87"/><path d="M8 41l7 24 7-24" fill="#ffcf77"/></g><circle cx="76" cy="51" r="14" fill="#7ccfc6"/><circle cx="331" cy="222" r="23" fill="#e9aa93"/><path d="M63 220h12m-6-6v12M355 111h12m-6-6v12M175 34h10m-5-5v10" stroke="#ffe0a2" stroke-width="3" stroke-linecap="round"/></svg>`;}
function header(){return `<header class="header"><button class="brand" data-action="home" aria-label="返回游戏大厅"><span class="brand-mark">✦</span><span>星际小队<small>STAR TEAM</small></span></button><span class="version">4 个文件夹 · 16 个游戏</span><button class="quiet" data-action="sound" aria-pressed="${settings.sound}">${settings.sound?'♫ 声音开启':'♫ 声音关闭'}</button></header>`;}
function shell(content){const focused=document.activeElement,identity=focused?.dataset?.action?{action:focused.dataset.action,value:focused.dataset.value,id:focused.dataset.id}:null;app.innerHTML=`<div class="page">${header()}${content}<footer>为 6–9 岁小朋友设计 · 和家长一起探索 <span><button class="quiet record-link" data-action="history">家长 · 最近的探索记录</button><button class="quiet record-link" data-action="j-records">家长 · 练习与休息记录</button>游戏练习，不提供诊断或治疗评估</span></footer></div>`;if(identity){const target=[...app.querySelectorAll('[data-action]')].find(el=>el.dataset.action===identity.action&&el.dataset.value===identity.value&&el.dataset.id===identity.id&&!el.disabled&&!el.closest('[inert]'));if(target)target.focus({preventScroll:true});}} 
function gameCard(g){return `<button class="game-card" data-action="choose" data-id="${g.id}" style="--accent:${palettes[g.color]}"><div class="card-top"><span class="game-index">${g.icon}</span><span class="tag">${g.tag}</span></div>${gameArtwork(g.id)}<h3>${g.name}</h3><p>${g.description}</p><span class="card-bottom">开始探索 <span>↗</span></span></button>`;}
function renderHome(){activeFolder=null;selected=null;session=null;view='home';message='';shell(`<main><section class="hero library-hero"><div><div class="eyebrow"><i></i>小小探索者，欢迎登舰</div><h1>今天，想练哪种本领？</h1><p>先打开一个任务文件夹，再选一个小游戏。<br>每次只看四个，慢慢选就好。</p><div class="hero-pills"><span>✧ 随时可以暂停</span><span>◌ 动态速度可调</span><span>♡ 慢慢来就好</span></div></div><div class="hero-art">${heroArt()}<span class="art-label">你的探索，从好奇心开始</span></div></section>${journey.homeCards()}<section class="missions"><div class="section-title"><div><span class="eyebrow">YOUR MISSION FOLDERS</span><h2>四个文件夹，四种探索方向。</h2></div><span class="soft-label">每个文件夹 · 4 个游戏</span></div><div class="folder-grid">${folders.map((folder,i)=>`<button class="folder-card" data-action="folder" data-id="${folder.id}" data-games="${folder.games.join(' ')}" style="--folder-color:${folder.color}" aria-label="打开${folder.name}，包含${folder.games.map(id=>games.find(g=>g.id===id).name).join('、')}"><div class="folder-cover"><div class="folder-mini-grid">${folder.games.map(id=>{const g=games.find(g=>g.id===id);return `<div class="folder-mini">${gameArtwork(id)}<span>${g.name}</span></div>`;}).join('')}</div></div><div class="folder-caption"><span class="folder-number">0${i+1}</span><div><h3>${folder.name}</h3><p>${folder.subtitle}</p></div><span class="folder-arrow">↗</span></div></button>`).join('')}</div></section><aside class="parent-note"><span>♡</span><div><b>给陪伴的大人</b><p>先选简单、静止或慢速模式。数字范围、记忆长度和移动速度可以分开调整；孩子想休息时，随时结束。</p></div></aside></main>`);}
function renderFolder(id=activeFolder?.id){const folder=folders.find(f=>f.id===id);if(!folder){renderHome();return;}activeFolder=folder;selected=null;session=null;view='folder';message='';shell(`<main class="folder-page"><button class="back" data-action="home">← 返回所有文件夹</button><div class="folder-page-title" style="--folder-color:${folder.color}"><div class="folder-emblem">${gameArtwork(folder.games[0])}</div><div><span class="eyebrow">MISSION FOLDER · 4 个游戏</span><h1>${folder.name}</h1><p>${folder.subtitle}。选一个任务开始吧。</p></div></div><div class="game-grid folder-games">${folder.games.map(id=>gameCard(games.find(g=>g.id===id))).join('')}</div><div class="folder-switches" aria-label="切换文件夹">${folders.map(f=>`<button class="secondary" data-action="folder" data-id="${f.id}" aria-pressed="${f.id===folder.id}">${f.name}</button>`).join('')}</div></main>`);}
function renderReady(){view='ready';session=null;message='';const g=selected;shell(`<main class="prepare"><button class="back" data-action="folder-back">← 返回${activeFolder?.name||"文件夹"}</button><section class="prepare-panel"><div class="prepare-art">${gameArtwork(g.id)}<span class="tag">${g.tag}</span></div><div class="prepare-copy"><div class="eyebrow">MISSION ${g.icon} · 准备出发</div><h1>${g.name}</h1><p class="instruction">${g.instruction}</p><div class="example"><b>先看一个例子</b><p>${g.example}</p></div><div class="settings">${g.id==='robot'?'':`<label>预设难度<select id="difficulty"><option value="easy" ${settings.difficulty==='easy'?'selected':''}>轻松探索</option><option value="challenge" ${settings.difficulty==='challenge'?'selected':''}>进阶挑战</option></select></label>`}<label>动态速度<select id="motion"><option value="still" ${settings.motion==='still'?'selected':''}>静止 / 减少动态</option><option value="slow" ${settings.motion==='slow'?'selected':''}>慢速</option><option value="normal" ${settings.motion==='normal'?'selected':''}>标准</option></select></label>${g.id==='orbit'?`<label>数字范围<select id="count">${[10,20,30,50].map(n=>`<option value="${n}" ${settings.count===n?'selected':''}>1–${n}</option>`).join('')}</select></label>`:''}</div>${extraSettings(g)}<div class="start-actions"><button class="primary" data-action="start">${journey.isTask()?'开始旅程短回合':'开始任务'} ↗</button>${journey.isTask()?'':'<button class="secondary" data-action="trial">试玩一小轮</button>'}</div><p class="micro">不倒计时催促 · 点错可以重试 · 随时暂停</p></div></section></main>`);}
function begin(trial=false){if(journey.isTask())trial=true;view=trial?'demo':'playing';message='';const hard=settings.difficulty==='challenge';session={id:selected.id,optionsConfig:optionsFor(selected.id),hintStage:0,trial,journey:journey.isTask(),hard,paused:false,phase:'input',clock:{elapsed:0,phaseElapsed:0},motionClock:0,correct:0,errors:0,hints:0,round:0,total:trial?1:3,feedback:'',hint:null};const s=session;
  if(s.id==='orbit'){s.n=trial?5:settings.count;s.layout=trial?shuffle(numbers(5)).map((value,slot)=>({value,ring:0,slot,count:5})):orbitLayout(s.n);s.target=1;}
  if(s.id==='pairs'){s.pairCount=trial?2:hard?6:3;s.cards=shuffle(Array.from({length:s.pairCount*2},(_,i)=>({id:i,kind:Math.floor(i/2)})));s.open=[];s.matched=[];}
  if(s.id==='signal'||s.id==='route'){newSequence();}
  if(s.id==='traffic'){s.total=trial?4:10;s.signals=shuffle([true,false,true,false,true,false,true,false,true,false]).slice(0,s.total);s.phase='prepare';s.responded=false;s.cue=-1;}
  if(s.id==='sort'){s.total=trial?3:10;newSort();}
  if(s.id==='search'){s.total=trial?2:6;newSearch();}
  if(s.id==='robot'){s.level=trial&&!s.journey?1:s.optionsConfig.level;Object.assign(s,robotLevel(s.level));s.position={...s.start};s.commands=[];s.path=[];s.executed=0;}
  batch2.init(s);journey.taskStarted();renderPlay();last=performance.now();}
function newSequence(){const s=session;const length=Math.min(7,(s.trial?2:s.optionsConfig.memoryCount|| (s.hard?3:2))+s.round);s.sequence=Array.from({length},()=>Math.floor(Math.random()*(s.id==='route'?6:4)));s.answer=[];s.phase='observe';s.clock.phaseElapsed=0;s.cue=-1;s.hint=null;}
function newSort(){const s=session;s.item={color:Math.floor(Math.random()*2),shape:Math.floor(Math.random()*2)};s.rule=s.hard&&s.round>=Math.ceil(s.total/2)?'shape':'color';s.hint=null;s.phase=s.round===Math.ceil(s.total/2)&&s.hard?'rule':'input';s.clock.phaseElapsed=0;}
function newSearch(){const s=session;const choices=shuffle(numbers(4).map(n=>n-1));s.targetKind=choices[0];const count=s.trial?4:s.hard?12:6;s.objects=shuffle(Array.from({length:count},(_,i)=>({id:i,kind:i===0?s.targetKind:choices[1+i%3]})));s.hint=null;s.clock.phaseElapsed=0;}
function phaseLabel(){const s=session;if(batch2.has(s.id))return batch2.label();if(s.phase==='observe')return '先看一看，记住顺序';if(s.phase==='rule')return '新规则，准备好再继续';if(s.phase==='run')return '机器人正在执行';if(s.phase==='checking'||s.phase==='swap')return '先看一看';return s.trial?'先轻松试一试':'轮到你啦';}
function goalText(){const s=session;if(batch2.has(s.id))return batch2.goal();if(s.id==='orbit')return `下一个：${s.target}`;if(s.id==='signal'||s.id==='route')return s.phase==='observe'?`记住 ${s.sequence.length} 个信号`:`已输入 ${s.answer.length} / ${s.sequence.length}`;if(s.id==='pairs')return `已找到 ${s.matched.length/2} / ${s.pairCount} 对`;if(s.id==='traffic')return s.phase==='cue'?(s.signals[s.round]?'✓ 通行 · 可以发射':'✋ 等待 · 先不动'):'飞船准备中';if(s.id==='sort')return s.rule==='color'?'现在按颜色分':'现在按形状分';if(s.id==='search')return `找出：${kindName(s.targetKind)}`;return `第 ${s.level} / 12 关 · 先排指令，再点执行`;}
function progress(){const s=session;if(batch2.has(s.id))return batch2.progress();return s.id==='orbit'?(s.target-1)/s.n:s.id==='pairs'?s.matched.length/(s.pairCount*2):s.id==='robot'?0:s.round/s.total;}
function renderPlay(){const s=session;const g=selected;const isSequence=['signal','route','cargo','tracking','chain'].includes(s.id);shell(`<main class="play">${journey.taskBanner()}<div class="play-heading"><button class="back" data-action="exit">← 返回准备</button><span class="soft-label">${s.journey?'旅程短回合':s.trial?'带练模式':g.tag} · ${s.id==='robot'?'第 '+s.level+' 关':settings.difficulty==='easy'?'轻松探索':'进阶挑战'}</span></div><section class="game-panel"><div class="mission-head"><div><span class="eyebrow">MISSION ${g.icon}</span><h1>${g.name}</h1></div><div class="play-tools"><label class="motion-control"><span>动态</span><select id="motion" aria-label="动态速度"><option value="still" ${settings.motion==='still'?'selected':''}>静止</option><option value="slow" ${settings.motion==='slow'?'selected':''}>慢速</option><option value="normal" ${settings.motion==='normal'?'selected':''}>标准</option></select></label><button class="secondary" data-action="pause">Ⅱ 暂停</button></div></div>${s.trial?`<div class="guided-tip" role="status"><b>🤖 小机器人带你玩</b><p>${trialInstruction()}</p></div>`:''}<div class="goal-bar"><span class="goal" id="goal">${goalText()}</span><span id="phase-label">${phaseLabel()}</span></div><div class="progress-track"><div style="width:${progress()*100}%"></div></div><div class="stage-wrap"><div class="stage ${s.id}-stage" id="stage" ${s.paused?'inert':''}>${renderScene()}</div>${s.paused?`<div class="pause-overlay" role="dialog" aria-modal="true" aria-labelledby="pause-title"><span class="pause-moon">☾</span><h2 id="pause-title">飞船停靠中</h2><p>休息一下，准备好再继续。</p><button class="primary" data-action="resume">继续探索</button><button class="quiet" data-action="exit">返回准备</button></div>`:''}</div><div class="feedback" role="status" aria-live="polite">${message||s.feedback||'慢慢来，想清楚再行动。'}</div><div class="game-bottom"><button class="secondary" data-action="hint" ${s.paused?'disabled':''}>✧ ${isSequence?'再看一次':'帮我一下'}</button><span>${batch2.has(s.id)?batch2.bottom():s.id==='orbit'?`找到 ${s.target-1} / ${s.n} 个数字`:s.id==='robot'?`已排 ${s.commands.length} / 20 条指令`:(s.id==='pairs'?`找到 ${s.matched.length/2} / ${s.pairCount} 对`:`第 ${Math.min(s.round+1,s.total)} / ${s.total} 段`)}</span><button class="quiet" data-action="restart">重新开始</button></div></section><p class="play-note">${g.instruction}</p></main>`);updateAnimated(0);}
function renderScene(){const s=session;if(batch2.has(s.id))return batch2.render();
  if(s.id==='orbit'){const maxRing=Math.max(...s.layout.map(v=>v.ring));return `<div class="orbit-scroll"><div class="orbit-board ${s.n>=30?'large':''}" data-rings="${maxRing+1}">${numbers(maxRing+1).map((_,i)=>`<div class="orbit-line ring-${i}" style="--radius:${orbitRadius(i,maxRing)}px"></div>`).join('')}<div class="orbit-core">✦<small>探索中</small></div>${s.layout.map(o=>`<button class="number ${o.value<s.target?'found':''} ${s.hint===o.value?'hinted':''}" data-action="number" data-value="${o.value}" data-ring="${o.ring}" data-slot="${o.slot}" data-count="${o.count}" ${o.value<s.target?'disabled':''} aria-label="数字 ${o.value}${o.value<s.target?'，已完成':''}">${o.value}</button>`).join('')}</div></div><p class="mobile-orbit-note">小屏幕多数字模式：静止完整布局，可上下滚动。</p>`;}
  if(s.id==='signal'){return `<div class="signal-grid">${icons.slice(0,4).map((icon,i)=>`<button class="signal-button ${s.cue===i?'lit':''}" style="--accent:${palettes[i]}" data-action="sequence" data-value="${i}" ${s.phase!=='input'?'disabled':''} aria-label="${['土星','月亮','太阳','星星'][i]}"><span>${icon}</span><small>${['土星','月亮','太阳','星星'][i]}</small></button>`).join('')}</div><div class="sequence-dots">${s.sequence.map((_,i)=>`<span class="${i<s.answer.length?'filled':''}"></span>`).join('')}</div>`;}
  if(s.id==='route'){return `<div class="route-board"><svg class="route-lines" viewBox="0 0 500 340" aria-hidden="true">${s.phase==='observe'?s.sequence.slice(1,Math.max(0,(s.playIndex??0)+1)).map((to,i)=>{const from=s.sequence[i];const p=routePos(from),q=routePos(to);return `<line x1="${p[0]}" y1="${p[1]}" x2="${q[0]}" y2="${q[1]}" stroke="#c6ac62" stroke-width="3" stroke-dasharray="5 8"/>`;}).join(''):''}</svg>${numbers(6).map((_,i)=>{const p=routePos(i);return `<button class="route-planet ${s.cue===i?'lit':''}" style="left:${p[0]/5}%;top:${p[1]/3.4}%;--accent:${palettes[i]}" data-action="sequence" data-value="${i}" ${s.phase!=='input'?'disabled':''} aria-label="${i+1}号星球"><span>${icons[i]}</span><small>${i+1} 号星</small>${s.cue===i?'<b class="visiting-ship">🚀</b>':''}</button>`;}).join('')}</div><div class="sequence-dots">${s.sequence.map((_,i)=>`<span class="${i<s.answer.length?'filled':''}"></span>`).join('')}</div>`;}
  if(s.id==='pairs'){return `<div class="pair-grid ${s.pairCount>3?'many':''}">${s.cards.map(card=>{const matched=s.matched.includes(card.id),open=matched||s.open.includes(card.id);return `<button class="pair-card ${open?'revealed':''} ${matched?'matched':''} ${s.hint===card.id?'hinted':''}" data-action="card" data-value="${card.id}" ${matched||s.phase!=='input'?'disabled':''} aria-label="${open?['土星','月亮','太阳','星星','火箭','卫星'][card.kind]:'未翻开卡片'}"><span>${open?icons[card.kind]:'✦'}</span><small>${matched?'已配对':open?'记住我':'点我翻开'}</small></button>`;}).join('')}</div>${s.phase==='swap'?'<p class="scene-tip">伙伴正在换位置，跟着看看。</p>':''}`;}
  if(s.id==='traffic'){const cue=s.phase==='cue';const go=s.signals[s.round];return `<div class="traffic-scene"><div class="traffic-light ${cue?(go?'go':'wait'):''}">${cue?(go?'✓':'✋'):'···'}<small>${cue?(go?'通行':'等待'):'准备信号'}</small></div><div class="launch-pad ${s.responded?'launched':''}"><span>🚀</span><div class="pad-line"></div></div><button class="primary launch-button" data-action="launch" ${s.responded?'disabled':''}>发射飞船 ↑</button><p class="scene-tip">通行才出发，等待时先不动。</p></div>`;}
  if(s.id==='sort'){return `<div class="sort-scene">${s.phase==='rule'?`<div class="rule-card"><span>↔</span><h2>换个规则试试</h2><p>接下来按「形状」分类，颜色不用管。</p><button class="primary" data-action="rule-ready">我准备好了</button></div>`:`<div class="conveyor"><div class="conveyor-item" id="conveyor-item">${shape(s.item.color*2+s.item.shape)}</div><div class="belt-dashes"></div></div><div class="bins">${[0,1].map(i=>`<button class="sort-bin ${s.hint===i?'hinted':''}" data-action="bin" data-value="${i}">${s.rule==='color'?`<span class="color-swatch color-${i}"></span>`:`<span class="bin-shape">${i===0?'●':'▲'}</span>`}<b>${s.rule==='color'?(i===0?'蓝色箱':'橙色箱'):(i===0?'圆形箱':'三角形箱')}</b><small>点击送进来 ↓</small></button>`).join('')}</div>`}</div>`;}
  if(s.id==='search'){return `<div class="search-target">目标 ${shape(s.targetKind)}</div><div class="asteroid-field">${s.objects.map((o,i)=>`<button class="asteroid ${s.hint===o.id?'hinted':''}" data-action="object" data-value="${o.id}" data-index="${i}" aria-label="${kindName(o.kind)}">${shape(o.kind)}</button>`).join('')}</div>`;}
  if(s.id==='robot'){return `<div class="robot-scene"><div class="robot-grid">${numbers(25).map((_,i)=>{const x=i%5,y=Math.floor(i/5),bot=s.position.x===x&&s.position.y===y,goal=s.goal[0]===x&&s.goal[1]===y,wall=s.walls.some(w=>w[0]===x&&w[1]===y);return `<div class="robot-cell ${wall?'wall':''} ${goal?'destination':''} ${s.path.some(p=>p.x===x&&p.y===y)?'visited':''}">${bot?`<span class="robot">🤖<b>${['↑','→','↓','←'][s.position.direction]}</b></span>`:wall?'▰':goal?'⭐':''}</div>`;}).join('')}</div><p class="scene-tip">机器人朝向：${['上 ↑','右 →','下 ↓','左 ←'][s.position.direction]} · 星星是目的地</p><div class="command-list" aria-label="已排指令">${s.commands.length?s.commands.map((c,i)=>`<span class="command ${i===s.executed&&s.phase==='run'?'active':''}">${i+1}. ${commandName(c)}</span>`).join(''):'还没有指令，先试试「前进」。'}</div><div class="robot-controls">${['F','L','R'].map(c=>`<button class="secondary" data-action="command" data-value="${c}" ${s.phase==='run'?'disabled':''}>${commandName(c)}</button>`).join('')}<button class="quiet" data-action="undo" ${s.phase==='run'?'disabled':''}>撤销</button><button class="quiet" data-action="clear" ${s.phase==='run'?'disabled':''}>清空</button><button class="primary" data-action="execute" ${s.phase==='run'||!s.commands.length?'disabled':''}>执行 ▶</button></div></div>`;}
  return '';}
function shape(kind){return `<span class="shape color-${Math.floor(kind/2)} ${kind%2?'triangle':'circle'}" aria-hidden="true"></span>`;}
function kindName(kind){return `${kind<2?'蓝色':'橙色'}${kind%2?'三角形':'圆形'}`;}
function commandName(c){return {F:'↑ 前进',L:'↶ 左转',R:'↷ 右转'}[c];}
function routePos(i){return [[85,75],[250,55],[415,75],[90,250],[255,265],[410,245]][i];}
function orbitRadius(i,max){return max===0?130:max===1?[90,205][i]:max===2?[85,160,245][i]:[85,150,225,300][i];}
function finish(){if(journey.taskFinished(session)){tone(true);return;}if(!session.trial){try{const records=JSON.parse(localStorage.getItem('star-team-history')||'[]');localStorage.setItem('star-team-history',JSON.stringify([{game:session.id,date:new Date().toISOString(),difficulty:settings.difficulty,options:session.optionsConfig,correct:session.correct,hints:session.hints,retries:session.errors,seconds:Math.round(session.clock.elapsed)},...(Array.isArray(records)?records:[])].slice(0,20)));}catch{}}view='done';session.phase='done';session.paused=false;message='';tone(true);renderDone();app.querySelector('.result-card .primary')?.focus({preventScroll:true});}
function renderDone(){const s=session;shell(`<main class="result"><section class="result-card"><span class="result-star">${{robot:'🤖',cargo:'📦',chain:'🚀',puzzle:'🧩',pattern:'✨',tracking:'🛰️'}[s.id]||'✦'}</span><div class="eyebrow">${s.trial?'第一次小小尝试':'MISSION COMPLETE'}</div><h1>${s.trial?'试玩完成啦！':'这次任务完成啦！'}</h1><p>${{robot:'机器人到站啦，你安排的路线成功了！',cargo:'货物装齐了，飞船准备启航！',chain:'每一步都完成了，物品送到了指定的地方！',pattern:'你找到了图案和数量变化的规律！',tracking:'你跟住了移动的卫星！',puzzle:'空间站拼好了，所有碎片都归位了！'}[s.id]||'你一步一步完成了探索。'}<br>可以继续探索，也可以休息一下。</p><div class="result-stats"><div><strong>${s.correct}</strong><span>${s.id==='pairs'?'找到的卡片':s.id==='robot'?'执行的指令':s.id==='puzzle'||s.id==='hanoi'?'有效移动次数':'完成的步骤'}</span></div><div><strong>${s.hints}</strong><span>使用的帮助</span></div><div><strong>${Math.floor(s.clock.elapsed/60)}:${String(Math.floor(s.clock.elapsed%60)).padStart(2,'0')}</strong><span>本轮探索时间</span></div></div><p class="micro">本轮有 ${s.errors} 次重试记录。它只是游戏记录，不代表能力评级。</p><div class="start-actions">${s.id==='robot'&&!s.trial&&s.level<12?'<button class="primary" data-action="next-level">探索下一关 →</button>':''}<button class="${s.id==='robot'&&!s.trial&&s.level<12?'secondary':'primary'}" data-action="${s.trial?'start':'restart'}">${s.trial?'开始正式任务':'再玩一次'} ↗</button><button class="secondary" data-action="folder-back">返回文件夹</button></div></section></main>`);}
function feedback(text,bad=false){message=text;if(bad)session.errors++;else tone(true);renderPlay();}
function tone(good){if(!settings.sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.value=good?523:330;gain.gain.setValueAtTime(.035,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+.18);osc.connect(gain);gain.connect(audioContext.destination);osc.start();osc.stop(audioContext.currentTime+.2);}catch{}}
function accept(action,value){const s=session;if(!s||s.paused||view==='done')return;if(batch2.has(s.id)){batch2.handle(action,value);return;}
  if(action==='number'&&s.id==='orbit'){const v=Number(value);if(v<s.target)return;if(v!==s.target){feedback('再找找看，我们要找的是 '+s.target+'。',true);return;}s.correct++;s.target++;s.hint=null;if(s.target>s.n){finish();return;}feedback('找到了！接着找 '+s.target+'。');}
  if(action==='sequence'&&(s.id==='signal'||s.id==='route')&&s.phase==='input'){const v=Number(value);if(v!==s.sequence[s.answer.length]){s.answer=[];feedback('这次顺序不一样。可以点「再看一次」，然后重试。',true);return;}s.answer.push(v);s.correct++;if(s.answer.length===s.sequence.length){s.round++;if(s.round>=s.total){finish();return;}message='记住了！来看下一组。';newSequence();renderPlay();}else feedback('对啦，继续下一颗。');}
  if(action==='card'&&s.id==='pairs'&&s.phase==='input'){const id=Number(value);if(s.open.includes(id)||s.matched.includes(id))return;s.open.push(id);s.hint=null;message='记住它的位置。';if(s.open.length===2){s.phase='checking';s.clock.phaseElapsed=0;const a=s.cards.find(c=>c.id===s.open[0]),b=s.cards.find(c=>c.id===s.open[1]);s.matchPending=a.kind===b.kind;if(!s.matchPending)s.errors++;message=s.matchPending?'找到一对啦！':'记住这两个位置，再找找看。';}renderPlay();}
  if(action==='launch'&&s.id==='traffic'){if(s.responded)return;if(s.phase!=='cue'){feedback('先等信号，飞船还在准备。',true);return;}if(!s.signals[s.round]){s.errors++;s.phase='retry';s.clock.phaseElapsed=0;message='这是等待信号。我们再试一次，先让飞船停好。';renderPlay();return;}s.responded=true;message='飞船收到通行信号，出发啦！';tone(true);renderPlay();}
  if(action==='bin'&&s.id==='sort'&&s.phase==='input'){const v=Number(value);if(v!==s.item[s.rule]){feedback('再看看上面的规则，这次按'+(s.rule==='color'?'颜色':'形状')+'分。',true);return;}s.correct++;s.round++;if(s.round>=s.total){finish();return;}message='送到正确的家啦。';newSort();renderPlay();}
  if(action==='rule-ready'&&s.id==='sort'){s.phase='input';message='现在按形状分，颜色不用管。';renderPlay();}
  if(action==='object'&&s.id==='search'){const item=s.objects.find(o=>o.id===Number(value));if(!item)return;if(item.kind!==s.targetKind){feedback('很接近，再同时看看颜色和形状。',true);return;}s.correct++;s.round++;if(s.round>=s.total){finish();return;}newSearch();feedback('找到了！下一颗目标准备好了。');}
  if(s.id==='robot'&&s.phase!=='run'){if(action==='command'){if(s.commands.length>=20){feedback('已经有 20 条指令，可以先执行或删掉一些。');return;}s.hintStage=0;s.commands.push(value);s.position={...s.start};s.path=[];message='指令排好了，可以继续添加或执行。';renderPlay();}if(action==='undo'||action==='clear'){s.hintStage=0;if(action==='undo')s.commands.pop();else s.commands=[];s.position={...s.start};s.path=[];message='可以重新安排路线。';renderPlay();}if(action==='execute'&&s.commands.length){s.phase='run';s.clock.phaseElapsed=0;s.executed=0;s.position={...s.start};s.path=[];message='看看机器人会走到哪里。';renderPlay();}}
}
function hint(){const s=session;if(!s||s.paused)return;if(batch2.has(s.id)){batch2.hint();return;}s.hints++;
  if(s.id==='signal'||s.id==='route'){s.answer=[];s.phase='observe';s.clock.phaseElapsed=0;s.cue=-1;message='再看一次，记住亮起的顺序。';}
  else if(s.id==='orbit'){s.hint=s.target;message='有一颗数字亮起了，看看是不是我们要找的。';}
  else if(s.id==='pairs'){if(s.phase!=='input'){s.hints--;return;}const exposed=s.cards.find(c=>c.id===s.open[0]);s.hint=exposed?s.cards.find(c=>c.kind===exposed.kind&&c.id!==exposed.id)?.id:s.cards.find(c=>!s.matched.includes(c.id))?.id;message='试试这张亮起的卡片，记住它的位置。';}
  else if(s.id==='sort'){s.hint=s.item[s.rule];message='正确的分类箱亮起来了。';}
  else if(s.id==='search'){s.hint=s.objects.find(o=>o.kind===s.targetKind).id;message='目标周围亮起了边框，再看看颜色和形状。';}
  else if(s.id==='traffic'){message='✓ 通行才发射；✋ 等待就先不点击。';}
  else {s.hintStage++;const solution=solveRobot(s.start,s.goal,s.size,s.walls);message=s.hintStage===1?'先看看机器人朝向，再找一条能避开墙的路线。':s.hintStage===2?`一条可行路线需要 ${solution.length} 条指令，转向不会前进。`:'可以按这条路线试试：'+solution.map(commandName).join('、')+'。';}
  renderPlay();}
function updateTemporal(dt){const s=session,t=s.clock.phaseElapsed;if(batch2.has(s.id)){batch2.tick(dt);return;}
  if((s.id==='signal'||s.id==='route')&&s.phase==='observe'){const slot=s.optionsConfig.playback,offset=t-.65,index=Math.floor(offset/slot);if(index>=s.sequence.length){s.phase='input';s.cue=-1;s.answer=[];message='轮到你啦，按刚才的顺序点击。';renderPlay();return;}const cue=offset>=0&&offset%slot<slot*.7?s.sequence[index]:-1;if(s.cue!==cue||s.playIndex!==Math.max(0,index)){s.cue=cue;s.playIndex=Math.max(0,index);if(cue>=0)tone(true);renderPlay();}}
  if(s.id==='pairs'&&s.phase==='checking'&&t>1.15){if(s.matchPending){s.matched.push(...s.open);s.correct+=2;}s.open=[];if(s.matched.length===s.cards.length){finish();return;}if(s.matchPending&&s.hard&&settings.motion!=='still'){s.phase='swap';s.clock.phaseElapsed=0;s.nextCards=[...s.cards];const unmatched=s.cards.filter(c=>!s.matched.includes(c.id));s.nextCards=s.cards.map(c=>s.matched.includes(c.id)?c:unmatched[(unmatched.indexOf(c)+1)%unmatched.length]);renderPlay();animateSwap();}else{s.phase='input';renderPlay();}}
  if(s.id==='pairs'&&s.phase==='swap'&&t>1.5){s.cards=s.nextCards;s.phase='input';message='伙伴换好位置了，可以继续翻牌。';renderPlay();}
  if(s.id==='traffic'){if((s.phase==='prepare'&&t>.8)||(s.phase==='retry'&&t>1.5)){s.phase='cue';s.clock.phaseElapsed=0;s.responded=false;message='看看信号再决定。';renderPlay();return;}if(s.phase==='cue'&&t>(s.hard?2.4:3.5)){if(s.signals[s.round]&&!s.responded){s.errors++;s.phase='retry';s.clock.phaseElapsed=0;message='刚才是通行信号，下一次可以点发射。';renderPlay();return;}s.correct++;s.round++;if(s.round>=s.total){finish();return;}s.phase='prepare';s.clock.phaseElapsed=0;s.responded=false;message='完成一个信号，准备下一个。';renderPlay();}}
  if(s.id==='robot'&&s.phase==='run'&&t>(settings.motion==='still'?.35:settings.motion==='slow'?.85:.55)){s.clock.phaseElapsed=0;const result=robotStep(s.position,s.commands[s.executed],s.size,s.walls);if(result.blocked){s.phase='input';feedback('前面走不通。可以撤销或修改指令，再执行一次。',true);return;}s.position=result.position;s.path.push({...s.position});s.executed++;if(s.position.x===s.goal[0]&&s.position.y===s.goal[1]){s.correct=s.executed;finish();return;}if(s.executed>=s.commands.length){s.phase='input';feedback('指令执行完了，还没到星星。可以添加指令后重新执行。',true);return;}renderPlay();}
}
function animateSwap(){const s=session,grid=document.querySelector('.pair-grid');if(!grid)return;const cards=[...grid.children];const slots=cards.map(el=>({left:el.offsetLeft,top:el.offsetTop}));const ratio=settings.motion==='still'?0:Math.min(1,s.clock.phaseElapsed/1.4);const eased=ratio*ratio*(3-2*ratio);cards.forEach((el,i)=>{const id=Number(el.dataset.value),from=slots[i],to=slots[s.nextCards.findIndex(c=>c.id===id)];el.style.transform=`translate(${(to.left-from.left)*eased}px,${(to.top-from.top)*eased}px)`;});}
function updateAnimated(){const s=session;if(!s)return;if(batch2.has(s.id)){batch2.animate();return;}if(s.id==='pairs'&&s.phase==='swap')animateSwap();const time=s.motionClock;
  if(s.id==='orbit'){const board=document.querySelector('.orbit-board');if(!board)return;const compact=board.clientWidth<550&&s.n>=30;board.classList.toggle('compact',compact);const rings=Number(board.dataset.rings),cx=board.clientWidth/2,cy=board.clientHeight/2,baseWidth=rings===4?690:rings===3?590:500,scale=Math.min(1,board.clientWidth/baseWidth);board.querySelectorAll('.number').forEach(el=>{if(compact){el.style.transform='none';el.style.left='';el.style.top='';return;}const ring=Number(el.dataset.ring),count=Number(el.dataset.count),slot=Number(el.dataset.slot);const angle=slot/count*Math.PI*2-Math.PI/2+time*(1+ring*.3)*(ring%2?-1:1),radius=orbitRadius(ring,rings-1)*scale;el.style.left=`${cx+Math.cos(angle)*radius}px`;el.style.top=`${cy+Math.sin(angle)*radius}px`;});board.querySelectorAll('.orbit-line').forEach((el,i)=>{const radius=orbitRadius(i,rings-1)*scale;el.style.width=el.style.height=`${radius*2}px`;});}
  if(s.id==='sort'){const item=document.querySelector('#conveyor-item');if(item)item.style.transform=`translateX(${Math.sin(time*1.7)*100}px)`;}
  if(s.id==='search'){const field=document.querySelector('.asteroid-field');if(!field)return;const cols=field.clientWidth<440?3:4,rows=Math.ceil(s.objects.length/cols);field.style.height=`${Math.max(240,rows*105)}px`;field.querySelectorAll('.asteroid').forEach((el,i)=>{const x=(i%cols+.5)/cols*field.clientWidth,y=(Math.floor(i/cols)+.5)/rows*field.clientHeight;el.style.left=`${x+Math.sin(time*2+i)*Math.min(15,field.clientWidth/cols/8)}px`;el.style.top=`${y+Math.cos(time*2+i)*12}px`;});}
}
function frame(now){const dt=Math.min((now-last)/1000,.1);last=now;journey.tick(dt,session);if(session&&!session.paused&&(view==='playing'||view==='demo')){session.clock=tickClock(session.clock,dt,false);session.motionClock+=dt*(settings.motion==='still'?0:settings.motion==='slow'?.10:.21);updateTemporal(dt);if(session&&view!=='done')updateAnimated();}requestAnimationFrame(frame);}
function action(action,value){if(journey.handle(action,value))return;if(['home','folder','folder-back','choose','history'].includes(action))journey.leave();if(action==='history'){renderHistory();return;}if(action==='clear-history'){try{localStorage.removeItem('star-team-history');}catch{}renderHistory();return;}if(action==='next-level'&&view==='done'&&session.id==='robot'&&session.level<12){profiles.robot={...profiles.robot,level:session.level+1};saveProfiles();begin();return;}if(action==='home'){renderHome();return;}if(action==='folder'){renderFolder(value);return;}if(action==='folder-back'){renderFolder();return;}if(action==='choose'){selected=games.find(g=>g.id===value);activeFolder=folders.find(f=>f.games.includes(value));renderReady();return;}if(action==='sound'){settings.sound=!settings.sound;saveSettings();if(journey.refresh())return;if(view==='home')renderHome();else if(view==='folder')renderFolder();else if(view==='ready')renderReady();else if(view==='done')renderDone();else if(view==='history')renderHistory();else renderPlay();return;}if(action==='start'||action==='trial'){begin(action==='trial');return;}if(action==='exit'){journey.snapshot();renderReady();return;}if(action==='restart'){begin(session?.trial??false);return;}if(action==='pause'&&session){session.paused=true;renderPlay();app.querySelector('[data-action="resume"]')?.focus();return;}if(action==='resume'&&session){session.paused=false;last=performance.now();renderPlay();app.querySelector('[data-action="pause"]')?.focus();return;}if(action==='hint'){hint();return;}accept(action,value);}
app.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(!button||button.disabled)return;if(button.dataset.action==='number'||button.dataset.action==='object'){if(button.closest('.compact')||e.detail===0)accept(button.dataset.action,button.dataset.value);return;}action(button.dataset.action,button.dataset.id??button.dataset.value);});
app.addEventListener('pointerdown',e=>{const button=e.target.closest('[data-action="number"],[data-action="object"]');if(!button||button.disabled||e.button!==0||!e.isPrimary||button.closest('.compact'))return;e.preventDefault();button.focus({preventScroll:true});accept(button.dataset.action,button.dataset.value);});
app.addEventListener('keydown',e=>{const button=e.target.closest('[data-action="number"],[data-action="object"]');if(button&&!button.disabled&&(e.key==='Enter'||e.key===' ')){e.preventDefault();accept(button.dataset.action,button.dataset.value);}});
app.addEventListener('change',e=>{if(journey.change(e.target))return;if(e.target.dataset.option&&view==='ready'){const key=e.target.dataset.option,value=Number(e.target.value);if(optionSpecs[key]?.includes(value)){profiles[selected.id]={...profiles[selected.id],[key]:value};saveProfiles();}return;}if(e.target.id==='motion')settings.motion=e.target.value;if(e.target.id==='difficulty')settings.difficulty=e.target.value;if(e.target.id==='count')settings.count=Number(e.target.value);saveSettings();if(view==='ready')renderReady();if(session&&view!=='done')updateAnimated();});
window.addEventListener('beforeunload',()=>journey.snapshot());
document.addEventListener('visibilitychange',()=>{if(document.hidden)journey.hidden();if(document.hidden&&session&&(view==='playing'||view==='demo')){session.paused=true;renderPlay();}});
reduced.addEventListener('change',e=>{if(e.matches){settings.motion='still';saveSettings();if(session&&view!=='done')renderPlay();}});
window.addEventListener('resize',()=>{if(session)updateAnimated();});
renderHome();requestAnimationFrame(frame);

document.addEventListener('keydown',e=>{if(e.target.matches('select,input,textarea')||!session||!['playing','demo'].includes(view))return;const index=['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'].indexOf(e.key);if(session.id==='reverse'&&index>=0){e.preventDefault();accept('b2-direction',String(index));}else if(e.key==='Escape'){e.preventDefault();action(session.paused?'resume':'pause');}});

function trialInstruction(){const s=session;
 if(s.id==='robot'){const path=solveRobot(s.start,s.goal,s.size,s.walls);return s.phase==='run'?'看机器人怎样一步一步执行你的指令。':s.commands.join('')===path.join('')?'路线排好了，点「执行」看看机器人能否到站。':'先试试这条路线：'+path.map(commandName).join('、')+'。转弯只改变朝向。';}
 if(s.id==='chain')return s.phase==='task-list'?'先读清单，每个物品都要先拿起，再送到指定收货点。':s.phase==='transport'?'这一步完成了，等物品送达。':'现在试试：'+s.taskLabels[s.steps[s.step]]+'。';
 if(s.id==='pattern')return s.patternMode==='shape'?'先把相同的几个伙伴看成一组，再找下一组的开头。':'先数前两组星星，再看看下一组增加或减少了多少。';
 if(s.id==='tracking')return s.phase==='mark'?'记住黄色框里的卫星。准备好后点「我记住了」。':s.phase==='track'?'先用眼睛跟着目标，等卫星停下来再点击。':'点出刚才带黄色框的卫星，忘记了也可以再看一次。';
 if(s.id==='cargo')return '先记住清单，再点击对应的货物；顺序可以不同。';
 return selected.example;
}
function renderHistory(){view='history';session=null;message='';let records=[];try{const saved=JSON.parse(localStorage.getItem('star-team-history')||'[]');if(Array.isArray(saved))records=saved.filter(r=>r&&games.some(g=>g.id===r.game)&&Number.isFinite(r.seconds)&&Number.isFinite(r.hints)&&Number.isFinite(r.retries)).slice(0,20);}catch{}
 const count=n=>Number.isFinite(n)?Math.max(0,Math.floor(n)):0;
 shell('<main class="history-page"><button class="back" data-action="home">← 返回游戏大厅</button><section class="history-panel"><div class="eyebrow">EXPLORATION LOG</div><h1>最近的探索记录</h1><p>仅记录这台设备最近 20 次完成的正式回合。带练不计入；刷新后仍保留。不同难度和帮助次数的回合不宜直接比较。</p>'+ (records.length?'<div class="history-list">'+records.map(r=>{const game=games.find(g=>g.id===r.game),date=new Date(r.date),validDate=!Number.isNaN(date.getTime());return '<article class="history-item"><div><b>'+game.name+'</b><small>'+(validDate?date.toLocaleString('zh-CN'):'本地记录')+' · '+(r.difficulty==='challenge'?'进阶挑战':'轻松探索')+(r.game==='robot'?' · 第 '+count(r.options?.level||1)+' 关':'')+'</small></div><p>'+count(r.hints)+' 次帮助 · '+count(r.retries)+' 次重试 · '+Math.floor(count(r.seconds)/60)+'分'+count(r.seconds)%60+'秒</p></article>';}).join('')+'</div><button class="secondary" data-action="clear-history">清空这台设备的记录</button>':'<div class="history-empty">✦<h2>还没有完成的正式回合</h2><p>完成一个任务后，记录会出现在这里。</p></div>')+'<p class="micro">这些是游戏过程记录，不代表能力评级。没有登录，也不会发送记录到服务器。</p></section></main>');
}

document.addEventListener('keydown',e=>{if(e.key!=='Tab'||!session?.paused)return;const controls=[...app.querySelectorAll('.pause-overlay button')];if(!controls.length)return;const i=controls.indexOf(document.activeElement);e.preventDefault();controls[(i+(e.shiftKey?-1:1)+controls.length)%controls.length].focus();});
