import {makePattern,makeChain,chainLabels,taskIcons,objectNames,destinationNames,trackingBodies,moveTracking} from './upgrades.js';
import {shuffle,numbers,moveTower,makePuzzle,slidePuzzle,puzzleSolved,solvePuzzle} from './logic.js';
export const extraGames=[
 {id:'reverse',name:'反向导航',tag:'换个方向',icon:'09',color:1,description:'看清导航规则，选择正确的方向。',instruction:'先看规则和大箭头，再点一个方向。进阶版有时跟随箭头，有时选择相反方向；换规则时会先提醒。',example:'箭头向上：跟随时点 ↑，反向时点 ↓。'},
 {id:'cargo',name:'星际货运清单',tag:'记住物品',icon:'10',color:7,description:'记住货运清单，再装好飞船的行李。',instruction:'先记住清单里的物品。清单收起后，从货运带中找出它们，物品的顺序不用相同。',example:'清单有电池和月亮，就把电池、月亮都装进飞船。'},
 {id:'tracking',name:'卫星追踪',tag:'跟随目标',icon:'11',color:5,description:'跟住亮起的卫星，看看它去了哪里。',instruction:'先记住带黄色边框的卫星。标记消失后，用眼睛跟住它们；停下后点击原来的目标。',example:'先看哪颗亮起来，再看它沿轨道移动。静止模式会用少量分步移动。'},
 {id:'hanoi',name:'星球搬家',tag:'多步规划',icon:'12',color:0,description:'帮大小星球搬到右边的新家。',instruction:'先点一个停靠点，选最上面的星球，再点目的地。每次只能搬最上面一颗，大星球不能放在小星球上。',example:'把两颗星球搬到右边：小的去中间，大的去右边，小的再去右边。'},
 {id:'puzzle',name:'太空拼图',tag:'空间规划',icon:'13',color:4,description:'移动空间站碎片，把数字拼回原位。',instruction:'点击空位旁边的碎片，让它滑入空位。按从左到右、从上到下的顺序拼好 1–8，空位留在右下角。',example:'空位在 8 的右边时，点 8 就可以把它向右移动一格。'},
 {id:'pattern',name:'星系补规律',tag:'发现规律',icon:'14',color:6,description:'看看星系排列，找出下一位伙伴。',instruction:'观察星球或星星的排列，选择问号处应该出现的图案。有的图案重复出现，有的数量逐渐增加。',example:'月亮、太阳、月亮、太阳，接下来是月亮。'},
 {id:'wait',name:'等信号再出发',tag:'耐心等待',icon:'15',color:3,description:'先做好准备，等指定信号再出发。',instruction:'上方会告诉你要等哪个信号。其他信号出现时先不点；指定信号出现后，点击出发。信号出现后会一直等你。',example:'要等星星时，看到月亮先等一等，看到星星才出发。'},
 {id:'chain',name:'小小任务链',tag:'记住步骤',icon:'16',color:2,description:'记住几个小任务，再按顺序完成。',instruction:'先看任务清单，再在场景中按顺序行动。拿到物品才能送去目的地，点错可以继续尝试。',example:'先拿电池，再把电池送到指定的地方。每轮物品和目的地会变化。'}
];
const glyphs=['🪐','🌙','☀️','⭐','🚀','🛰️','💎','🔋'];
const names=['土星','月亮','太阳','星星','火箭','卫星','宝石','电池'];
const arrows=['↑','→','↓','←'],directions=['上','右','下','左'];
export function createBatch2(api){
 const has=id=>extraGames.some(g=>g.id===id);
 const s=()=>api.session(),settings=()=>api.settings();
 function phase(name){s().phase=name;s().clock.phaseElapsed=0;}
 function nextReverse(){const g=s();g.arrow=Math.floor(Math.random()*4);g.reverse=g.hard&&Math.floor(g.round/2)%2===1;g.hint=null;phase(g.round>0&&g.hard&&g.round%2===0?'new-rule':'input');}
 function nextCargo(){const g=s();g.list=shuffle(numbers(8).map(n=>n-1)).slice(0,g.trial?2:Math.min(6,(g.optionsConfig.memoryCount|| (g.hard?4:2))+g.round));g.options=shuffle(numbers(8).map(n=>n-1));g.picked=[];g.hint=null;phase('memorize');}
 function nextTracking(){const g=s();g.count=g.trial?4:(g.optionsConfig.trackingCount|| (g.hard?6:4));g.targetCount=g.trial?1:(g.optionsConfig.trackingTargets|| (g.hard?2:1));g.bodies=trackingBodies(g.count);g.satellites=shuffle(numbers(g.count).map(n=>n-1));g.targets=shuffle(g.satellites).slice(0,g.targetCount);g.picked=[];g.angle=0;g.lastStep=0;g.hint=null;phase('mark');}
 function nextPattern(){const g=s();let pattern;for(let attempt=0;attempt<20;attempt++){pattern=makePattern(g.hard,g.round);if(JSON.stringify(pattern.patternValues)!==g.lastPattern)break;}Object.assign(g,pattern);g.lastPattern=JSON.stringify(pattern.patternValues);g.hint=null;g.hintStage=0;phase('input');}
 function nextWait(){const g=s();g.waitTarget=g.hard?shuffle([3,6,7])[0]:3;g.decoys=shuffle(numbers(8).map(n=>n-1).filter(n=>n!==g.waitTarget));g.waitDuration=2.6+Math.random()*2.5;g.decoyIndex=0;g.hint=null;phase('waiting');}
 function nextChain(){const g=s();Object.assign(g,makeChain(g.trial?1:(g.optionsConfig.chainPairs||(g.hard?2:1))));g.taskLabels=chainLabels(g.deliveries);g.step=0;g.inventory=null;g.hint=null;phase('task-list');}
 function init(g){if(!has(g.id))return;
  if(g.id==='reverse'){g.total=g.trial?3:8;nextReverse();}
  if(g.id==='cargo'){g.total=g.trial?1:3;nextCargo();}
  if(g.id==='tracking'){g.total=g.trial?1:3;nextTracking();}
  if(g.id==='hanoi'){g.total=1;g.diskCount=g.hard&&!g.trial?3:2;g.towers=[numbers(g.diskCount).reverse(),[],[]];g.selectedPeg=null;g.history=[];g.moveCount=0;}
  if(g.id==='puzzle'){g.total=1;g.board=makePuzzle(g.trial?3:g.hard?18:6);g.history=[];g.moveCount=0;}
  if(g.id==='pattern'){g.total=g.trial?2:6;nextPattern();}
  if(g.id==='wait'){g.total=g.trial?2:g.hard?7:5;nextWait();}
  if(g.id==='chain'){g.total=g.trial?1:2;nextChain();}
 }
 function goal(){const g=s();if(g.id==='reverse')return g.reverse?'反向导航 · 选择相反方向':'跟随导航 · 选择箭头方向';if(g.id==='cargo')return g.phase==='memorize'?`记住这 ${g.list.length} 件货物`:`已装好 ${g.picked.length} / ${g.list.length} 件`;if(g.id==='tracking')return g.phase==='mark'?`记住 ${g.targetCount} 颗亮起的卫星`:g.phase==='track'?'眼睛跟着卫星走':`找到原来的 ${g.targetCount} 颗卫星`;if(g.id==='hanoi')return '把所有星球搬到右边';if(g.id==='puzzle')return '拼好 1–8，空位留在右下角';if(g.id==='pattern')return '问号处应该是什么？';if(g.id==='wait')return `看到${names[g.waitTarget]} ${glyphs[g.waitTarget]} 才出发`;if(g.id==='chain')return g.phase==='task-list'?`记住这 ${g.steps.length} 步任务`:`已完成 ${g.step} / ${g.steps.length} 步`;}
 function label(){const g=s();return {memorize:'先记住清单，再挑选',mark:'记住黄色边框的目标',track:'先观察，停下后再点击','new-rule':'新规则，准备好再继续','task-list':'先记住任务顺序',transport:'正在送达，稍等一下',sliding:'碎片正在滑动',waiting:'还没到信号，先等一等',go:'信号到了，可以出发',departure:'飞船出发啦'}[g.phase]??(g.trial?'先轻松试一试':'轮到你啦');}
 function progress(){const g=s();if(g.id==='hanoi')return g.towers[2].length/g.diskCount;if(g.id==='puzzle')return g.board.filter((n,i)=>n===((i+1)%9)).length/9;return g.round/g.total;}
 function bottom(){const g=s();if(g.id==='hanoi'||g.id==='puzzle')return `已移动 ${g.moveCount} 次`;return `第 ${Math.min(g.round+1,g.total)} / ${g.total} 轮`;}
 function token(n){return `<span class="cargo-symbol">${glyphs[n]}</span><small>${names[n]}</small>`;}
 function patternToken(n){return s().patternMode==='shape'?`<span class="pattern-planet">${glyphs[n]}</span>`:`<span class="star-count" aria-label="${n}颗星星">${'⭐'.repeat(n)}<small>${n} 颗</small></span>`;}
 function render(){const g=s();
  if(g.id==='reverse')return `<div class="reverse-scene">${g.phase==='new-rule'?`<div class="rule-card"><span>↔</span><h2>切换导航规则</h2><p>接下来${g.reverse?'选择箭头的相反方向':'跟着箭头的方向走'}。</p><button class="primary" data-action="b2-rule">我准备好了</button></div>`:`<div class="navigation-orbit"><span class="navigation-ship" id="navigation-ship">🚀</span><span class="direction-cue" aria-label="箭头向${directions[g.arrow]}">${arrows[g.arrow]}</span></div><p class="scene-tip">${g.reverse?'这次反着走':'这次跟着走'} · 规则一直在上方显示</p><div class="direction-controls">${arrows.map((a,i)=>`<button class="direction-button ${g.hint===i?'hinted':''}" data-action="b2-direction" data-value="${i}" aria-label="向${directions[i]}">${a}<small>${directions[i]}</small></button>`).join('')}</div>`}</div>`;
  if(g.id==='cargo')return `<div class="cargo-scene">${g.phase==='memorize'?`<div class="list-banner"><h2>这次要带上……</h2><div class="cargo-list">${g.list.map(n=>`<div class="list-item">${token(n)}</div>`).join('')}</div><p class="scene-tip">看清楚再开始，不用按清单顺序挑选。</p><button class="primary" data-action="b2-cargo-ready">我记住了，开始装货</button></div>`:`<div class="cargo-conveyor"><div class="cargo-rail" id="cargo-rail">${g.options.map(n=>`<button class="cargo-item ${g.picked.includes(n)?'packed':''} ${g.hint===n?'hinted':''}" data-action="b2-cargo" data-value="${n}" ${g.picked.includes(n)?'disabled':''} aria-label="${names[n]}">${token(n)}${g.picked.includes(n)?'<b>✓ 已装好</b>':''}</button>`).join('')}</div></div><div class="cargo-bag"><span>🚀 行李舱</span>${g.picked.map(n=>`<span aria-label="${names[n]}">${glyphs[n]}</span>`).join('')}</div>`}</div>`;
  if(g.id==='tracking')return `<div class="tracking-scene"><div class="satellite-board" id="satellite-board"><div class="satellite-orbit"></div><span class="tracking-earth">🌍</span>${g.satellites.map((id,i)=>`<button class="satellite ${g.phase==='mark'&&g.targets.includes(id)?'marked':''} ${g.picked.includes(id)?'picked':''}" data-action="b2-satellite" data-value="${id}" data-slot="${i}" ${g.phase!=='input'||g.picked.includes(id)?'disabled':''} aria-label="卫星 ${id+1}"><span>🛰️</span>${g.phase==='mark'&&g.targets.includes(id)?'<small>记住我</small>':''}</button>`).join('')}</div><p class="scene-tip">${g.phase==='mark'?'黄色边框是这次的目标。':g.phase==='track'?'标记收起来了，跟着目标看一看。':'卫星停好了，点击你跟住的那几颗。'}</p>${g.phase==='mark'?'<button class="primary" data-action="b2-track-ready">我记住了，开始移动</button>':''}</div>`;
  if(g.id==='hanoi')return `<div class="hanoi-scene"><div class="hanoi-board" id="hanoi-board"><div class="hanoi-pegs">${[0,1,2].map(i=>`<button class="hanoi-peg ${g.selectedPeg===i?'selected':''} ${g.hint===i?'hinted':''}" data-action="b2-peg" data-value="${i}" ${g.phase==='transport'?'disabled':''} aria-label="${['左边','中间','右边'][i]}停靠点，${g.towers[i].length}颗星球"><span class="peg-pole"></span><span class="peg-base"></span><small>${['出发点','中转站','新家 ⭐'][i]}</small></button>`).join('')}</div><div class="hanoi-disks">${g.towers.map((tower,peg)=>tower.map((disk,level)=>`<span class="hanoi-disk disk-${disk}" data-disk="${disk}" data-peg="${peg}" data-level="${level}">${disk===1?'🌙':disk===2?'🪐':'🌍'}</span>`).join('')).join('')}</div></div><p class="scene-tip">${g.selectedPeg===null?'先点一个停靠点，选择最上面的星球。':'已选好星球，再点它要去的停靠点。'}</p><button class="secondary light" data-action="b2-undo" ${!g.history.length||g.phase==='transport'?'disabled':''}>↶ 撤销上一步</button></div>`;
  if(g.id==='puzzle')return `<div class="puzzle-scene"><div class="puzzle-board" id="puzzle-board">${g.board.map((tile,index)=>tile?`<button class="puzzle-tile ${g.hint===tile?'hinted':''}" data-action="b2-tile" data-value="${tile}" data-index="${index}" ${g.phase==='sliding'?'disabled':''} aria-label="碎片 ${tile}"><span>${tile}</span><small>${['🌙','⭐','🪐','🛰️','🚀','🌍','☀️','💎'][tile-1]}</small></button>`:`<div class="puzzle-blank" data-index="${index}" aria-label="空位">空位</div>`).join('')}</div><div class="puzzle-reference"><span>目标排列</span><div>${[1,2,3,4,5,6,7,8,''].map(n=>`<i>${n}</i>`).join('')}</div></div><button class="secondary light" data-action="b2-undo" ${!g.history.length||g.phase==='sliding'?'disabled':''}>↶ 撤销上一步</button></div>`;
  if(g.id==='pattern')return `<div class="pattern-scene"><p class="scene-tip">${g.patternMode==='shape'?'这些伙伴一组一组地重复出现。':'看看每一组的星星数量怎样变化。'}</p><div class="pattern-sequence">${g.patternValues.map(n=>`<div class="pattern-term">${patternToken(n)}</div>`).join('')}<div class="pattern-term question">?</div></div><p class="scene-tip">选一个伙伴，补上问号。</p><div class="pattern-options">${g.options.map(n=>`<button class="pattern-option ${g.hint===n?'hinted':''}" data-action="b2-pattern" data-value="${n}" aria-label="${g.patternMode==='shape'?names[n]:n+'颗星星'}">${patternToken(n)}</button>`).join('')}</div></div>`;
  if(g.id==='wait'){const go=g.phase==='go'||g.phase==='departure';return `<div class="wait-scene"><div class="wanted-signal">要等的信号 ${token(g.waitTarget)}</div><div class="waiting-signal ${go?'ready-signal':''}" aria-label="当前信号：${names[go?g.waitTarget:g.decoys[g.decoyIndex]]}">${glyphs[go?g.waitTarget:g.decoys[g.decoyIndex]]}<small>${go?'信号到了！':'还没到指定信号'}</small></div><span class="waiting-ship" id="waiting-ship">🚀</span><button class="primary" data-action="b2-depart" ${g.phase==='departure'?'disabled':''}>准备好后，点这里出发 ↑</button><p class="scene-tip">目标信号出现后，会一直等你。慢慢来。</p></div>`;}
  if(g.id==='chain')return `<div class="chain-scene">${g.phase==='task-list'?`<div class="list-banner"><h2>先记住这几个步骤</h2><ol class="task-list">${g.steps.map((task,i)=>`<li data-task="${task}" class="${i<g.step?'task-done':''}"><span>${i+1}</span><b>${taskIcons[task]}</b>${g.taskLabels[task]}${i<g.step?' ✓':''}</li>`).join('')}</ol><button class="primary" data-action="b2-chain-ready">我记住了，开始行动</button></div>`:`<div class="task-world">${Object.keys(g.taskLabels).map(task=>`<button class="task-object ${g.hint===task?'hinted':''}" data-action="b2-task" data-value="${task}" ${g.phase==='transport'?'disabled':''}><span>${taskIcons[task]}</span><b>${g.taskLabels[task]}</b>${destinationNames[task]?`<small>${taskIcons[g.deliveries.find(d=>d.destination===task).object]} 收货点</small>`:''}</button>`).join('')}</div><div class="inventory"><span>🎒 手里的物品</span><strong>${g.inventory?taskIcons[g.inventory]:'还没有'}</strong></div><div class="courier">${g.phase==='transport'?'<span id="task-courier">🚀</span>':'✦'}</div>`}</div>`;
  return '';}
 function completedRound(next){const g=s();g.round++;if(g.round>=g.total){api.finish();return;}next();api.setMessage('这一轮完成啦，准备下一轮。');api.render();}
 function handle(action,value){const g=s();if(!has(g.id))return false;
  if(action==='b2-rule'&&g.phase==='new-rule'){phase('input');api.render();}
  if(action==='b2-direction'&&g.id==='reverse'&&g.phase==='input'){const expected=(g.arrow+(g.reverse?2:0))%4;if(Number(value)!==expected){api.feedback('再看一次导航规则，'+(g.reverse?'这次要反着走。':'这次跟着箭头走。'),true);}else{g.correct++;completedRound(nextReverse);}}
  if(action==='b2-cargo-ready'&&g.id==='cargo'&&g.phase==='memorize'){phase('input');api.setMessage('清单收起来了，开始挑选货物吧。');api.render();}
  if(action==='b2-cargo'&&g.id==='cargo'&&g.phase==='input'){const n=Number(value);if(g.picked.includes(n))return true;if(!g.list.includes(n)){api.feedback('这件货物不在清单里。可以点「再看一次」确认。',true);}else{g.picked.push(n);g.correct++;g.hint=null;if(g.picked.length===g.list.length)completedRound(nextCargo);else api.feedback('装好一件啦，再找找其他货物。');}}
  if(action==='b2-track-ready'&&g.id==='tracking'&&g.phase==='mark'){phase('track');g.lastStep=0;api.setMessage('用眼睛跟住刚才亮起的目标。');api.render();}
  if(action==='b2-satellite'&&g.id==='tracking'&&g.phase==='input'){const n=Number(value);if(g.picked.includes(n))return true;if(!g.targets.includes(n)){api.feedback('再想想刚才亮起的是哪颗，可以点「再看一次」。',true);}else{g.picked.push(n);g.correct++;if(g.picked.length===g.targets.length)completedRound(nextTracking);else api.feedback('找到一颗了，还有一颗。');}}
  if(action==='b2-peg'&&g.id==='hanoi'&&g.phase==='input'){const peg=Number(value);g.hint=null;if(g.selectedPeg===null){if(!g.towers[peg].length)api.feedback('这个停靠点没有星球，请先选有星球的地方。');else{g.selectedPeg=peg;api.setMessage('选好了，再点要去的停靠点。');api.render();}}else if(g.selectedPeg===peg){g.selectedPeg=null;api.render();}else{const from=g.selectedPeg,next=moveTower(g.towers,from,peg);if(!next){api.feedback('大星球不能放在小星球上，换个停靠点试试。',true);}else{g.history.push(g.towers.map(t=>[...t]));g.transport={disk:g.towers[from].at(-1),from,to:peg,fromLevel:g.towers[from].length-1,toLevel:g.towers[peg].length};g.towers=next;g.selectedPeg=null;g.moveCount++;g.correct++;phase('transport');api.setMessage('星球正在搬家。');api.render();}}}
  if(action==='b2-tile'&&g.id==='puzzle'&&g.phase==='input'){const tile=Number(value),next=slidePuzzle(g.board,tile);if(!next){api.feedback('只能移动空位旁边的碎片。',true);}else{g.history.push([...g.board]);g.slide={tile,from:g.board.indexOf(tile),to:g.board.indexOf(0)};g.board=next;g.hint=null;g.moveCount++;g.correct++;phase('sliding');api.setMessage('碎片滑入空位啦。');api.render();}}
  if(action==='b2-undo'&&g.phase==='input'&&g.history?.length){if(g.id==='hanoi'){g.towers=g.history.pop();g.selectedPeg=null;}if(g.id==='puzzle')g.board=g.history.pop();g.moveCount=Math.max(0,g.moveCount-1);g.correct=Math.max(0,g.correct-1);g.hint=null;api.feedback('撤销好了，可以试另一种走法。');}
  if(action==='b2-pattern'&&g.id==='pattern'&&g.phase==='input'){if(Number(value)!==g.answer)api.feedback('再看看前面的排列，试试另一个答案。',true);else{g.correct++;completedRound(nextPattern);}}
  if(action==='b2-depart'&&g.id==='wait'){if(g.phase==='waiting'){phase('waiting');api.feedback('还没有出现指定信号，我们再等一次。',true);}else if(g.phase==='go'){g.correct++;phase('departure');api.setMessage('等到指定信号啦，飞船出发！');api.render();}}
  if(action==='b2-chain-ready'&&g.id==='chain'&&g.phase==='task-list'){phase('input');api.setMessage('清单收起来了，按记住的顺序完成任务。');api.render();}
  if(action==='b2-task'&&g.id==='chain'&&g.phase==='input'){if(value!==g.steps[g.step])api.feedback('这一步顺序不对，可以点「再看一次」看看清单。',true);else{if(Object.hasOwn(objectNames,value))g.inventory=value;else g.inventory=null;g.step++;g.correct++;g.hint=null;phase('transport');api.setMessage('完成一步啦，物品正在送达。');api.render();}}
  return true;
 }
 function hint(){const g=s();g.hints++;
  if(g.id==='reverse'){g.hint=(g.arrow+(g.reverse?2:0))%4;api.setMessage('正确的方向亮起来了，再看看规则。');}
  if(g.id==='cargo'){phase('memorize');api.setMessage('再看一下这次的货物清单。');}
  if(g.id==='tracking'){phase('mark');api.setMessage('再看一下原来的目标，它们现在停在这些位置。');}
  if(g.id==='hanoi'){if(g.phase!=='input'){g.hints--;return;}const queue=[{t:g.towers,path:[]}],seen=new Set([JSON.stringify(g.towers)]);let solution;for(let i=0;i<queue.length;i++){const node=queue[i];if(node.t[2].length===g.diskCount){solution=node.path;break;}for(let from=0;from<3;from++)for(let to=0;to<3;to++){const t=moveTower(node.t,from,to),key=JSON.stringify(t);if(t&&!seen.has(key)){seen.add(key);queue.push({t,path:[...node.path,[from,to]]});}}}if(solution?.length){g.hint=solution[0][0];g.selectedPeg=null;api.setMessage(`先选${['左边','中间','右边'][solution[0][0]]}最上面的星球，再搬到${['左边','中间','右边'][solution[0][1]]}。`);}}
  if(g.id==='puzzle'){if(g.phase!=='input'){g.hints--;return;}const solution=solvePuzzle(g.board);if(solution?.length){g.hint=solution[0];api.setMessage(`可以先把数字 ${g.hint} 移进空位。`);}}
  if(g.id==='pattern'){g.hintStage++;if(g.hintStage===1)api.setMessage(g.patternMode==='shape'?'找找哪些伙伴是一组重复出现的。':'比较前两组，再比较第二、第三组，数量变多还是变少？');else if(g.hintStage===2)api.setMessage(g.patternClue);else{g.hint=g.answer;api.setMessage('下一组亮起来了，再看看它为什么合适。');}}
  if(g.id==='wait')api.setMessage(`等${names[g.waitTarget]} ${glyphs[g.waitTarget]} 出现后再出发，其他信号先不点。`);
  if(g.id==='chain'){if(g.phase==='transport'){g.hints--;return;}phase('task-list');api.setMessage('再看一次清单，已完成的步骤会打勾。');}
  api.render();
 }
 function tick(dt){const g=s(),t=g.clock.phaseElapsed;
  if(g.id==='cargo'&&g.phase==='memorize'&&g.optionsConfig.observation&&t>g.optionsConfig.observation){phase('input');api.setMessage('清单收起来了，开始装货吧。');api.render();}
  if(g.id==='tracking'&&g.phase==='mark'&&g.optionsConfig.observation&&t>g.optionsConfig.observation){phase('track');g.lastStep=0;api.render();}
  if(g.id==='tracking'&&g.phase==='track'){const board=document.querySelector('#satellite-board'),radius=board?Math.min(board.clientWidth,board.clientHeight)/2-42:120;const speed=settings().motion==='normal'?1.2:.65;if(settings().motion==='still'){const step=Math.floor(t/1.5);if(step>g.lastStep){g.bodies=moveTracking(g.bodies,.35,64/radius);g.lastStep=step;}}else g.bodies=moveTracking(g.bodies,dt*speed,64/radius);if(t>5){phase('input');api.setMessage('卫星停好了，找出原来的目标。');api.render();}}
  if(g.id==='hanoi'&&g.phase==='transport'&&t>(settings().motion==='still'?.15:.8)){phase('input');if(g.towers[2].length===g.diskCount){api.finish();return;}api.setMessage('搬好了，可以继续。');api.render();}
  if(g.id==='puzzle'&&g.phase==='sliding'&&t>(settings().motion==='still'?.1:.35)){phase('input');if(puzzleSolved(g.board)){api.finish();return;}api.render();}
  if(g.id==='wait'&&g.phase==='waiting'){if(t>=g.waitDuration){phase('go');api.setMessage('指定信号出现啦，准备好后就出发。');api.render();}else{const index=Math.floor(t/.9)%g.decoys.length;if(index!==g.decoyIndex){g.decoyIndex=index;api.render();}}}
  if(g.id==='wait'&&g.phase==='departure'&&t>.7)completedRound(nextWait);
  if(g.id==='chain'&&g.phase==='task-list'&&g.optionsConfig.observation&&t>g.optionsConfig.observation){phase('input');api.setMessage('按清单顺序，开始行动吧。');api.render();}
  if(g.id==='chain'&&g.phase==='transport'&&t>.65){if(g.step===g.steps.length){completedRound(nextChain);return;}phase('input');api.setMessage('准备好下一步了吗？');api.render();}
 }
 function animate(){const g=s(),time=g.motionClock;
  const ship=document.querySelector('#navigation-ship');if(ship)ship.style.transform=`translateY(${Math.sin(time*3)*12}px)`;
  const rail=document.querySelector('#cargo-rail');if(rail)rail.style.transform=`translateX(${Math.sin(time*2)*10}px)`;
  const board=document.querySelector('#satellite-board');if(board){const radius=Math.min(board.clientWidth,board.clientHeight)/2-42;board.querySelectorAll('.satellite').forEach(el=>{const body=g.bodies[Number(el.dataset.slot)];el.style.left=`${board.clientWidth/2+body.x*radius}px`;el.style.top=`${board.clientHeight/2+body.y*radius}px`;});}
  const hanoi=document.querySelector('#hanoi-board');if(hanoi){hanoi.querySelectorAll('.hanoi-disk').forEach(el=>{let peg=Number(el.dataset.peg),level=Number(el.dataset.level),lift=0;if(g.phase==='transport'&&Number(el.dataset.disk)===g.transport.disk&&settings().motion!=='still'){const p=Math.min(1,g.clock.phaseElapsed/.75);peg=g.transport.from+(g.transport.to-g.transport.from)*p;level=g.transport.fromLevel+(g.transport.toLevel-g.transport.fromLevel)*p;lift=Math.sin(p*Math.PI)*90;}el.style.left=`${(peg+.5)/3*100}%`;el.style.bottom=`${49+level*39+lift}px`;});}
  const puzzle=document.querySelector('#puzzle-board');if(puzzle){puzzle.querySelectorAll('[data-index]').forEach(el=>{let index=Number(el.dataset.index),x=index%3,y=Math.floor(index/3);if(g.phase==='sliding'&&Number(el.dataset.value)===g.slide.tile&&settings().motion!=='still'){const p=Math.min(1,g.clock.phaseElapsed/.3);x=(g.slide.from%3)*(1-p)+(g.slide.to%3)*p;y=Math.floor(g.slide.from/3)*(1-p)+Math.floor(g.slide.to/3)*p;}el.style.left=`calc(${x*100/3}% + 5px)`;el.style.top=`calc(${y*100/3}% + 5px)`;});}
  const waiting=document.querySelector('#waiting-ship');if(waiting)waiting.style.transform=g.phase==='departure'&&settings().motion!=='still'?`translate(${g.clock.phaseElapsed*80}px,${-g.clock.phaseElapsed*50}px)`:`translateY(${Math.sin(time*3)*5}px)`;
  const courier=document.querySelector('#task-courier');if(courier)courier.style.transform=settings().motion==='still'?'none':`translateX(${(g.clock.phaseElapsed/.65-.5)*180}px)`;
 }
 return {has,init,goal,label,progress,bottom,render,handle,hint,tick,animate};
}
