export const gifts=[
 {id:'star-snack',name:'星星小饼干',kind:'snack',price:10,icon:'⭐',color:'#ffdb8c'},
 {id:'mint-bow',name:'薄荷领结',kind:'bow',price:15,icon:'🎀',color:'#80d9c1'},
 {id:'star-hat',name:'星星小帽',kind:'hat',price:20,icon:'🎩',color:'#ffdb8c'},
 {id:'fish-snack',name:'小鱼点心',kind:'snack',price:25,icon:'🐟',color:'#97d6ef'},
 {id:'coral-bow',name:'珊瑚领结',kind:'bow',price:30,icon:'🎀',color:'#f3a6b1'},
 {id:'moon-hat',name:'月亮睡帽',kind:'hat',price:35,icon:'🌙',color:'#b9b0ed'},
 {id:'fruit-snack',name:'彩虹小点心',kind:'snack',price:40,icon:'🍓',color:'#eab0cc'},
 {id:'rainbow-bow',name:'彩虹领结',kind:'bow',price:45,icon:'🎀',color:'#bcb2ed'},
 {id:'space-hat',name:'星际探险帽',kind:'hat',price:50,icon:'🪖',color:'#8dccdf'}
];
export function rewardRegistry(gameIds,robotLevels=12){return Object.fromEntries(gameIds.flatMap(id=>id==='robot'?Array.from({length:robotLevels},(_,i)=>['robot:'+ (i+1),10]):[[id,10]]));}
export const rewardLimit=registry=>Object.values(registry).reduce((sum,n)=>sum+n,0);
export const giftBudget=()=>gifts.reduce((sum,g)=>sum+g.price,0);
export const emptyPetState=()=>({version:1,credits:{},purchases:[],selected:null,pets:{cat:{hat:null,bow:null,snack:null},dog:{hat:null,bow:null,snack:null}}});
export const earnedPoints=state=>Object.values(state.credits).reduce((sum,n)=>sum+n,0);
export const balance=state=>earnedPoints(state)-state.purchases.reduce((sum,p)=>sum+p.paid,0);
export function normalizePetState(raw,registry){const state=emptyPetState();if(raw?.version!==1)return state;
 for(const [id,value] of Object.entries(raw.credits||{}))if(Object.hasOwn(registry,id)&&[5,10].includes(value))state.credits[id]=value;
 if(Array.isArray(raw.purchases))for(const p of raw.purchases){const item=gifts.find(g=>g.id===p?.id);if(item&&p.paid===item.price&&!state.purchases.some(v=>v.id===p.id)&&balance(state)>=p.paid)state.purchases.push({id:p.id,paid:p.paid});}
 if(['cat','dog'].includes(raw.selected))state.selected=raw.selected;
 for(const type of ['cat','dog'])for(const kind of ['hat','bow','snack']){const id=raw.pets?.[type]?.[kind];if(gifts.some(g=>g.id===id&&g.kind===kind)&&state.purchases.some(p=>p.id===id))state.pets[type][kind]=id;}
 return state;
}
export function awardPoints(state,registry,session){const id=session.id==='robot'?'robot:'+session.level:session.id;if(!Object.hasOwn(registry,id))return {state,added:0};const total=session.trial?5:10,before=state.credits[id]||0,added=Math.max(0,total-before);if(!added)return {state,added:0};return {state:{...state,credits:{...state.credits,[id]:total}},added};}
export function buyGift(state,id){const item=gifts.find(g=>g.id===id);if(!item)return {state,error:'没有找到这件礼物。'};if(state.purchases.some(p=>p.id===id))return {state,error:'已经兑换过啦，可以直接送给伙伴。'};if(balance(state)<item.price)return {state,error:'星星还不够，先挑一件已经拥有的礼物吧。'};return {state:{...state,purchases:[...state.purchases,{id,paid:item.price}]},error:null};}
export function giveGift(state,id){const item=gifts.find(g=>g.id===id),type=state.selected;if(!type)return {state,error:'先选一位小伙伴吧。'};if(!item||!state.purchases.some(p=>p.id===id))return {state,error:'这件礼物还没有兑换。'};return {state:{...state,pets:{...state.pets,[type]:{...state.pets[type],[item.kind]:id}}},error:null};}
const key='star-team-pets',names={cat:'小猫',dog:'小狗'};
const itemFor=id=>gifts.find(g=>g.id===id);
export function petArtwork(type,profile={}){const cat=type==='cat',fur=cat?'#edbb84':'#ccaa86',hat=itemFor(profile.hat),bow=itemFor(profile.bow),snack=itemFor(profile.snack);
 const head=cat?'<path d="M113 132L107 70L151 111M186 109L231 71L226 140" fill="'+fur+'" stroke="#9f775e" stroke-width="3"/><path d="M118 111L116 87L137 108M202 108L224 88L220 115" fill="#e69d9c"/>':'<path d="M120 114Q76 76 77 150Q80 187 112 159M220 114Q264 76 263 150Q260 187 229 159" fill="#946d54"/>';
 const hatSvg=!hat?'':hat.id==='star-hat'?'<path d="M134 99L144 60Q170 51 197 60L205 99" fill="'+hat.color+'"/><ellipse cx="170" cy="99" rx="48" ry="9" fill="#e6ae54"/><path d="M170 64l4 8 9 1-7 6 2 9-8-5-8 5 2-9-7-6 9-1Z" fill="#fff5d5"/>':hat.id==='moon-hat'?'<path d="M125 104Q148 40 223 52L211 97Q163 73 148 113Z" fill="'+hat.color+'"/><circle cx="223" cy="52" r="10" fill="#f7e8c4"/><path d="M157 78a13 13 0 1 0 17-16 10 10 0 0 1-17 16" fill="#fff3be"/>':'<path d="M125 101Q126 50 170 49Q214 50 217 101Z" fill="'+hat.color+'"/><path d="M119 105h102" stroke="#5c93ae" stroke-width="12" stroke-linecap="round"/><circle cx="170" cy="74" r="14" fill="#e5f5f7"/><path d="M166 66l13 8-13 8Z" fill="#77b4c8"/>';
 const bowSvg=!bow?'':`<g transform="translate(170 199)"><path d="M-5 0L-32-17Q-42 0-32 17L-5 5M5 0L32-17Q42 0 32 17L5 5" fill="${bow.color}" stroke="#fff" stroke-opacity=".5" stroke-width="2"/>${bow.id==='rainbow-bow'?'<path d="M-31-11L-11 0M-32 1L-12 8M31-11L11 0" stroke="#ffda87" stroke-width="5"/>':''}<circle r="8" fill="${bow.id==='mint-bow'?'#51a996':'#c47a9e'}"/></g>`;
 return `<svg class="pet-art" viewBox="0 0 340 300" role="img" aria-label="${names[type]||'小伙伴'}${hat?'戴着'+hat.name:''}${bow?'，系着'+bow.name:''}"><ellipse cx="170" cy="273" rx="103" ry="13" fill="#0e1b3028"/><path d="M217 238Q281 241 253 205" fill="none" stroke="${fur}" stroke-width="17" stroke-linecap="round"/><ellipse cx="170" cy="225" rx="58" ry="48" fill="${fur}"/><ellipse cx="170" cy="226" rx="28" ry="29" fill="#fff0d9"/>${head}<ellipse cx="170" cy="146" rx="64" ry="54" fill="${fur}"/><ellipse cx="170" cy="164" rx="29" ry="23" fill="#fff0d9"/><path d="M135 143q8-9 16 0M190 143q8-9 16 0" stroke="#53433e" stroke-width="4" fill="none" stroke-linecap="round"/><path d="M163 155q7-5 14 0l-7 7Z" fill="#97665c"/><path d="M170 162v6m-12 0q12 13 24 0" fill="none" stroke="#765345" stroke-width="3" stroke-linecap="round"/>${cat?'<path d="M128 160l-25-4m25 13l-25 4m109-13l25-4m-25 13l25 4" stroke="#986f55" stroke-width="2"/>':''}<ellipse cx="134" cy="265" rx="25" ry="12" fill="#f0d0a4"/><ellipse cx="206" cy="265" rx="25" ry="12" fill="#f0d0a4"/>${hatSvg}${bowSvg}${snack?`<g><ellipse cx="266" cy="257" rx="29" ry="13" fill="#edf0e8"/><text x="266" y="258" text-anchor="middle" font-size="30">${snack.icon}</text></g>`:''}</svg>`;
}
export function createPets(api){const registry=rewardRegistry(api.games.map(g=>g.id),api.robotLevels||12);let state=emptyPetState(),notice='',message='',pending=null,active=false,storageOK=true;
 function read(){if(!storageOK)return state;try{const raw=localStorage.getItem(key);return raw?normalizePetState(JSON.parse(raw),registry):emptyPetState();}catch{return state;}}
 state=read();
 function save(next){state=next;try{localStorage.setItem(key,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}return state;}
 function wallet(blocked=false){state=read();return blocked?`<span class="wallet-button" aria-label="可用积分 ${balance(state)} 星星">✦ ${balance(state)}</span>`:`<button class="wallet-button" data-action="pet-open" aria-label="打开宠物与礼物，可用积分 ${balance(state)} 星星">✦ <span>${balance(state)}</span></button>`;}
 function gameProgress(id){state=read();const keys=Object.keys(registry).filter(key=>id==='robot'?key.startsWith('robot:'):key===id);return keys.reduce((sum,key)=>sum+(state.credits[key]||0),0)+' / '+keys.reduce((sum,key)=>sum+registry[key],0)+' 已收集';}
 function selectCompanion(type){if(!['cat','dog'].includes(type))return false;state=read();save({...state,selected:type});return true;}
 function companionArtwork(type){state=read();return petArtwork(type,state.pets[type]);}
 function buddyHTML(mode){state=read();if(!state.selected)return '';return '<div class="selected-buddy">'+petArtwork(state.selected,state.pets[state.selected])+'<div><b>'+names[state.selected]+'陪你'+(mode==='rest'?'休息':'探索')+'</b><p>按自己的节奏，慢慢来就好。</p></div></div>';}
 function homeCard(){state=read();return `<section class="pet-entry"><button data-action="pet-open"><div class="pet-entry-avatar">${state.selected?petArtwork(state.selected,state.pets[state.selected]):'<span aria-hidden="true">🐱 🐶</span>'}</div><div><span class="eyebrow">MY LITTLE SPACE FRIEND</span><h2>${state.selected?'我的'+names[state.selected]+'伙伴':'选一位小伙伴，一起探索'}</h2><p>完成小游戏，收集星星，送一份小礼物。<br>帽子、领结、小点心，兑换后一直保留。</p></div><span class="pet-entry-points">✦ ${balance(state)}<small>可用星星</small></span></button></section>`;}
 function award(session){state=read();const result=awardPoints(state,registry,session);if(result.added)save(result.state);notice=result.added?`这次获得 ${result.added} 颗星星，已放进礼物口袋。`:'这个任务的星星已经收集过啦。重玩和使用帮助都不会扣分。';return result.added;}
 function noticeHTML(blocked=false){return notice?`<div class="points-notice" role="status"><span>✦ ${notice}</span>${blocked?'':'<button class="quiet" data-action="pet-open">去看看小伙伴 →</button>'}<button class="quiet" data-action="pet-dismiss" aria-label="收起积分提示">×</button></div>`:'';}
 function giftCards(ownedOnly=false){const items=gifts.filter(g=>ownedOnly?state.purchases.some(p=>p.id===g.id):!state.purchases.some(p=>p.id===g.id));return items.length?`<div class="pet-gift-grid">${items.map(g=>{const owned=state.purchases.some(p=>p.id===g.id),used=state.selected&&state.pets[state.selected][g.kind]===g.id;return `<article class="pet-gift-card"><div class="gift-symbol ${g.kind}" style="--gift-color:${g.color}">${g.kind==='bow'?'<svg viewBox="0 0 100 60" aria-hidden="true"><path d="M45 23L13 5Q1 30 13 55L45 37M55 23L87 5Q99 30 87 55L55 37" fill="currentColor"/><circle cx="50" cy="30" r="13" fill="currentColor" stroke="#fff8" stroke-width="3"/></svg>':g.icon}</div><h3>${g.name}</h3><p>${owned?'已兑换 · 可以反复使用':'✦ '+g.price+' 星星'}</p>${owned?`<button class="secondary" data-action="pet-give" data-value="${g.id}" ${state.selected?'':'disabled'}>${used&&g.kind!=='snack'?'正在佩戴':g.kind==='snack'?'请伙伴吃一点':'送给'+(names[state.selected]||'伙伴')}</button>`:`<button class="${balance(state)>=g.price?'primary':'secondary'}" data-action="pet-buy-request" data-value="${g.id}" ${balance(state)<g.price?'disabled':''}>${balance(state)>=g.price?'兑换这件礼物':'还差 '+(g.price-balance(state))+' 星星'}</button>`}</article>`;}).join('')}</div>`:ownedOnly?'<p class="pet-empty">礼物口袋还空着。玩一小轮喜欢的游戏，再来看看吧。</p>':'<p class="pet-empty">这批礼物都在口袋里啦。想玩就玩，也可以安心休息。</p>';}
 function render(){active=true;state=read();const type=state.selected,profile=state.pets[type]||{},currentHat=itemFor(profile.hat),currentBow=itemFor(profile.bow),currentSnack=itemFor(profile.snack);
 const main=`<div class="pet-main-content" ${pending?'inert':''}><button class="back" data-action="pet-home">← 返回游戏大厅</button><section class="pet-heading"><div><div class="eyebrow">A FRIEND, ALWAYS HERE</div><h1>我的星际小伙伴</h1><p>把游戏获得的星星换成虚拟帽子、领结或点心，让孩子自己选礼物、装扮喜欢的伙伴。休息不扣分，也不需要为奖励继续玩。</p></div><div class="pet-wallet"><strong>✦ ${balance(state)}</strong><span>可用星星</span><small>累计收集 ${earnedPoints(state)} / ${rewardLimit(registry)}</small></div></section><section class="pet-cabin"><div class="pet-window" aria-hidden="true">✦ · ☾ · ✧</div>${type?petArtwork(type,profile):'<div class="pet-empty-art">🐱 <span>或</span> 🐶</div>'}<div class="pet-cabin-copy"><h2>${type?names[type]+'正在陪着你':'想邀请谁来陪你？'}</h2><p>${type?'礼物可以共用，换伙伴也会记住它的打扮。':'选小猫或小狗，之后随时可以切换。'}</p><div class="pet-choice">${['cat','dog'].map(t=>`<button class="secondary" data-action="pet-select" data-value="${t}" aria-pressed="${type===t}">${t==='cat'?'🐱':'🐶'} ${names[t]}${type===t?' · 已选择':''}</button>`).join('')}</div>${type?`<div class="pet-outfit">${[currentHat?.name,currentBow?.name,currentSnack?'点心：'+currentSnack.name:null].filter(Boolean).join(' · ')||'还没有礼物，陪伴已经开始啦。'}</div><div class="pet-choice"><button class="quiet" data-action="pet-touch">轻轻打个招呼</button>${currentHat||currentBow?'<button class="quiet" data-action="pet-undress">收好帽子和领结</button>':''}</div>`:''}</div></section><p class="pet-feedback" role="status">${message||'没有喂养倒计时，伙伴不会因为你休息而难过。'}${!storageOK?' 当前浏览器没有允许保存，关闭页面后可能丢失这次进度。':''}</p><section class="pet-closet"><div class="section-title"><div><span class="eyebrow">MY GIFT POCKET</span><h2>我的礼物口袋 · ${state.purchases.length} / ${gifts.length}</h2></div></div>${giftCards(true)}</section><section class="pet-shop"><div class="section-title"><div><span class="eyebrow">LITTLE GIFT SHOP</span><h2>给伙伴挑一份礼物</h2></div></div><p>每件只兑换一次，永久保留。小点心也是虚拟礼物，可以反复互动。</p>${giftCards()}</section><details class="pet-rules"><summary>给家长 · 积分与兑换规则</summary><p>目前 16 款游戏，机器人有 12 关，共 ${Object.keys(registry).length} 个奖励任务。每个任务首次短回合 5 分，完整回合累计到 10 分；先玩短回合再完成完整回合，补发 5 分。难度、动态速度、用时、提示和重试不影响积分。</p><p>当前累计最多 ${rewardLimit(registry)} 分，${gifts.length} 件礼物总价 ${giftBudget()} 分，全部完整任务各完成一次即可兑换全部礼物。同一任务重复完成不会反复加分。休息不计分，提前结束不扣分。积分从本版本启用后的完成开始记录。</p><p>猫狗共用礼物口袋，各自保留打扮。没有饥饿、连续签到、限时促销或排行榜；积分不代表能力评级。积分和宠物仅保存在当前浏览器，不跨设备同步，也不能兑换实物。</p></details></div>`;
 const item=itemFor(pending),dialog=item?`<div class="pet-confirm-overlay"><section class="pet-confirm" role="dialog" aria-modal="true" aria-labelledby="pet-confirm-title"><h2 id="pet-confirm-title">兑换${item.name}？</h2><p>使用 ${item.price} 颗星星，兑换后永久保留。<br>现在有 ${balance(state)} 颗，兑换后剩 ${Math.max(0,balance(state)-item.price)} 颗。</p><div class="pet-choice"><button class="primary" data-action="pet-buy-confirm" data-value="${item.id}">确认兑换</button><button class="secondary" data-action="pet-buy-cancel">再看看</button></div></section></div>`:'';
 api.show(`<main class="pet-page">${main}${dialog}</main>`);if(item)document.querySelector('[data-action="pet-buy-confirm"]')?.focus();
 }
 function handle(action,value){if(!action.startsWith('pet-'))return false;
  if(action==='pet-open'){api.enter();message='';pending=null;render();}
  else if(action==='pet-dismiss'){notice='';api.refresh();}
  else if(action==='pet-home'){active=false;pending=null;api.home();}
  else if(action==='pet-select'&&['cat','dog'].includes(value)){state=read();save({...state,selected:value});message=names[value]+'来啦！你可以把已有的礼物送给它。';render();}
  else if(action==='pet-buy-request'){state=read();const item=itemFor(value);if(item&&!state.purchases.some(p=>p.id===value)&&balance(state)>=item.price){pending=value;render();}}
  else if(action==='pet-buy-cancel'){const id=pending;pending=null;render();document.querySelector(`[data-action="pet-buy-request"][data-value="${id}"]`)?.focus();}
  else if(action==='pet-buy-confirm'&&pending===value){state=read();const result=buyGift(state,value);pending=null;if(result.error)message=result.error;else{save(result.state);message=itemFor(value).name+'已经放进礼物口袋。'+(state.selected?'点「送给伙伴」就能使用。':'先选小猫或小狗，再送给它。');}render();}
  else if(action==='pet-give'){state=read();const result=giveGift(state,value);if(result.error)message=result.error;else{save(result.state);const item=itemFor(value);message=item.kind==='snack'?names[state.selected]+'收到了'+item.name+'，谢谢你的小礼物！':names[state.selected]+'戴上了'+item.name+'。礼物一直在口袋里。';}render();}
  else if(action==='pet-undress'&&state.selected){state=read();save({...state,pets:{...state.pets,[state.selected]:{...state.pets[state.selected],hat:null,bow:null}}});message='帽子和领结已收好，随时可以再戴上。';render();}
  else if(action==='pet-touch'){message='小伙伴向你打了个招呼。今天做到这里，也很好。';render();}
  return true;
 }
 function leave(){active=false;pending=null;}
 function refresh(){if(!active)return false;render();return true;}
 document.addEventListener('keydown',e=>{if(!active||!pending)return;if(e.key==='Escape'){e.preventDefault();handle('pet-buy-cancel');}if(e.key==='Tab'){const controls=[...document.querySelectorAll('.pet-confirm button')],i=controls.indexOf(document.activeElement);e.preventDefault();controls[(i+(e.shiftKey?-1:1)+controls.length)%controls.length]?.focus();}});
 window.addEventListener('storage',e=>{if(e.key===key||e.key===null){state=read();if(active)render();else api.refresh();}});
 return {wallet,selectCompanion,companionArtwork,buddyHTML,gameProgress,homeCard,award,noticeHTML,handle,refresh,leave,clearNotice:()=>{notice='';}};
}
