import {folders} from './library.js';
const recordsKey='star-team-rounds',passportKey='star-team-passport',limit=5000;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const integer=n=>Number.isFinite(n)&&n>=0?Math.min(1000000,Math.floor(n)):0;
const modes={formal:'正式回合',trial:'试玩',journey:'定制／旅程短回合',legacy:'旧记录'};
export const metrics={retries:{name:'重试次数',unit:'次'},hints:{name:'帮助次数',unit:'次'},seconds:{name:'有效游戏时间',unit:'秒'},correct:{name:'有效操作数',unit:'次'}};
export function localDay(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
export function roundRecord(session,settings,date=new Date()){
 const initial=session.settingsAtStart||settings;
 const relevant={signal:['memoryCount','playback'],route:['memoryCount','playback'],cargo:['memoryCount','observation'],tracking:['trackingCount','trackingTargets','observation'],chain:['chainPairs','observation'],robot:['level']};
 const options={};for(const key of relevant[session.id]||[])if(Number.isFinite(session.optionsConfig?.[key]))options[key]=session.optionsConfig[key];
 const context={difficulty:initial.difficulty,motion:initial.motion,options,mode:session.journey?'journey':session.trial?'trial':'formal',numbers:session.n||0,pairs:session.pairCount||0,rounds:session.total||0,level:session.id==='robot'?session.level:0,layout:session.compactAtFinish?'compact':'regular'};
 return {version:2,id:session.roundId,date:date.toISOString(),game:session.id,mode:context.mode,difficulty:context.difficulty,context,comparable:!session.motionChanged&&!session.layoutChanged&&!!session.settingsAtStart,correct:integer(session.correct),hints:integer(session.hints),retries:integer(session.errors),seconds:integer(Math.round(session.clock.elapsed))};
}
export function contextKey(record){return record.comparable&&record.context?record.game+':'+JSON.stringify(record.context):'unknown';}
export function addRound(records,record){return records.some(r=>r.id===record.id)?records:[record,...records].slice(0,limit);}
export function cleanRounds(raw,ids){if(!Array.isArray(raw))return [];const seen=new Set();return raw.filter(r=>r&&typeof r.id==='string'&&r.id.length<120&&!seen.has(r.id)&&ids.includes(r.game)&&Number.isFinite(new Date(r.date).getTime())&&Object.hasOwn(modes,r.mode)&&['hints','retries','seconds'].every(k=>Number.isFinite(r[k])&&r[k]>=0)&&(!r.comparable||r.version===2&&r.context&&['easy','challenge'].includes(r.context.difficulty)&&['still','slow','normal'].includes(r.context.motion))&&seen.add(r.id)).slice(0,limit).map(r=>({...r,hints:integer(r.hints),retries:integer(r.retries),seconds:integer(r.seconds),correct:r.correct==null?null:integer(r.correct)}));}
export function legacyRounds(raw,ids){if(!Array.isArray(raw))return [];return cleanRounds(raw.map((r,i)=>r?{...r,id:'legacy:'+i+':'+r.date,version:1,mode:'legacy',comparable:false}:null),ids);}
export const emptyPassport=()=>({version:1,counts:Object.fromEntries(folders.map(f=>[f.id,0])),days:Object.fromEntries(folders.map(f=>[f.id,[]]))});
export function normalizePassport(raw){const state=emptyPassport();if(raw?.version!==1)return state;for(const f of folders){state.counts[f.id]=Number.isSafeInteger(raw.counts?.[f.id])&&raw.counts[f.id]>=0?raw.counts[f.id]:0;state.days[f.id]=Array.isArray(raw.days?.[f.id])?[...new Set(raw.days[f.id].filter(d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)))].slice(-366):[];}return state;}
export function stampPassport(state,game,day){const folder=folders.find(f=>f.games.includes(game));if(!folder||state.days[folder.id].includes(day))return {state,added:false};return {state:{version:1,counts:{...state.counts,[folder.id]:state.counts[folder.id]+1},days:{...state.days,[folder.id]:[...state.days[folder.id],day].slice(-366)}},added:true};}
export function csvRounds(rows,names){const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return '\uFEFF'+[['完成时间','游戏','模式','难度','重试次数','帮助次数','有效时间（秒）','有效操作数','可否同条件比较','设置'],...rows.map(r=>[r.date,names[r.game],modes[r.mode],r.difficulty,r.retries,r.hints,r.seconds,r.correct,r.comparable?'可比较':'条件不完整或中途改变',JSON.stringify(r.context||{})])].map(row=>row.map(quote).join(',')).join('\r\n');}
export function chartSVG(rows,metric){
 const usable=rows.filter(r=>Number.isFinite(r[metric]));if(!usable.length)return '<div class="chart-empty">完成一次相同设置的游戏后，这里会出现记录。</div>';
 const max=Math.ceil(Math.max(4,...usable.map(r=>r[metric]))/4)*4,left=55,right=690,top=26,bottom=238;
 const points=usable.map((r,i)=>({r,x:usable.length===1?(left+right)/2:left+i/(usable.length-1)*(right-left),y:bottom-r[metric]/max*(bottom-top)}));
 const grid=Array.from({length:5},(_,i)=>{const y=bottom-i/4*(bottom-top),value=max*i/4;return `<line x1="${left}" x2="${right}" y1="${y}" y2="${y}" stroke="#ffffff13"/><text x="${left-10}" y="${y+4}" text-anchor="end" fill="#9cb1ce" font-size="12">${Number(value.toFixed(1))}</text>`;}).join('');
 return `<svg class="record-chart" viewBox="0 0 720 280" role="img" aria-label="${metrics[metric].name}记录曲线，共${usable.length}个完成回合。具体数据见下方表格。">${grid}${usable.length>1?`<polyline points="${points.map(p=>p.x+','+p.y).join(' ')}" fill="none" stroke="#91d7ca" stroke-width="3"/>`:''}${points.map(({r,x,y},i)=>`<circle cx="${x}" cy="${y}" r="5" fill="#ffda91"><title>第 ${i+1} 回合 · ${esc(new Date(r.date).toLocaleString('zh-CN'))} · ${r[metric]} ${metrics[metric].unit}</title></circle>`).join('')}<text x="${left}" y="268" fill="#9cb1ce" font-size="12">第 1 回合</text><text x="${right}" y="268" text-anchor="end" fill="#9cb1ce" font-size="12">第 ${usable.length} 回合</text></svg>`;
}
export function createProgress(api){
 const ids=api.games.map(g=>g.id),names=Object.fromEntries(api.games.map(g=>[g.id,g.name]));let records=[],passport=emptyPassport(),recordsOK=true,passportOK=true,active=false,screen='history',game=null,group=null,metric='retries',clearing=false,downloadMessage='';
 try{const saved=JSON.parse(localStorage.getItem(recordsKey));records=cleanRounds(saved?.records,ids);if(!saved?.legacyImported){records=addLegacy(records,legacyRounds(JSON.parse(localStorage.getItem('star-team-history')),ids));writeRecords();}}catch{records=[];}
 try{passport=normalizePassport(JSON.parse(localStorage.getItem(passportKey)));}catch{}
 function addLegacy(rows,old){const existing=new Set(rows.map(r=>r.id));return [...rows,...old.filter(r=>!existing.has(r.id))].slice(0,limit);}
 function read(){if(recordsOK)try{const raw=localStorage.getItem(recordsKey);if(raw)records=cleanRounds(JSON.parse(raw).records,ids);}catch{}if(passportOK)try{const raw=localStorage.getItem(passportKey);if(raw)passport=normalizePassport(JSON.parse(raw));}catch{}}
 function writeRecords(){try{localStorage.setItem(recordsKey,JSON.stringify({version:2,legacyImported:true,records}));recordsOK=true;}catch{recordsOK=false;}}
 function writePassport(){try{localStorage.setItem(passportKey,JSON.stringify(passport));passportOK=true;}catch{passportOK=false;}}
 function complete(session,settings){
  read();if(session.recorded)return {stampAdded:false};session.roundId??=crypto.randomUUID();session.compactAtFinish=!!document.querySelector('.orbit-board.compact');const record=roundRecord(session,settings);
  const next=addRound(records,record);if(next===records){session.recorded=true;return {stampAdded:false};}records=next;writeRecords();session.recorded=true;
  const stamped=stampPassport(passport,session.id,localDay());passport=stamped.state;if(stamped.added)writePassport();return {stampAdded:stamped.added};
 }
 function totalStamps(){return Object.values(passport.counts).reduce((sum,n)=>sum+n,0);}
 function passportButton(){read();return `<button class="secondary" data-action="passport-open">星际护照 · ${totalStamps()} 枚探索章</button>`;}
 function passportCard(){read();return `<section class="passport-teaser"><div><b>重玩，也留下新的探索足迹</b><p>已经收集 ${totalStamps()} 枚探索章。每个分类每天第一次完成盖一枚，隔天重玩仍可积累。</p></div><button class="secondary" data-action="passport-open">打开星际护照 →</button></section>`;}
 function show(content){api.show(`<main class="progress-page"><button class="back" data-action="progress-home">← 返回文件夹</button>${content}</main>`);}
 function renderPassport(){show(`<section class="progress-panel"><span class="eyebrow">我的星际护照</span><h1 tabindex="-1">每次回来，都能留下足迹</h1><p>累计 ${totalStamps()} 枚探索章。隔几天再来，它们也一直在。</p><div class="passport-grid">${folders.map(f=>{const count=passport.counts[f.id],page=Math.floor(count/8)+1,filled=count%8;return `<article class="passport-category"><h2>${f.name}</h2><div class="passport-seal" style="--seal-color:${f.color}">✦<small>${count} 枚</small></div><p>已完成 ${Math.floor(count/8)} 页 · 第 ${page} 页</p><div class="passport-slots" aria-label="本页已有${filled}枚探索章，共8个位置">${Array.from({length:8},(_,i)=>`<span class="${i<filled?'filled':''}" aria-hidden="true">${i<filled?'✦':'·'}</span>`).join('')}</div></article>`;}).join('')}</div><p class="micro">完成任何游戏都记录回合；每个分类每天最多盖一枚章。每满 8 枚，永久保存一页星图，之后仍可继续积累。试玩和旅程也可以，休息不记成绩、不盖游戏章。</p><p class="micro">没有连续签到、补签或断签损失，也不要求一天玩完四类。想回来就回来，想休息就休息。印章不兑换实物，不代表能力。</p>${!passportOK?'<p role="status">当前浏览器无法保存，关闭后可能丢失这次印章。</p>':''}</section>`);}
 function contextLabel(r){const c=r.context;if(!r.comparable||!c)return '条件不完整／中途改变 · 仅看明细';const labels={memoryCount:'记忆项数',playback:'播放秒数',observation:'观察秒数',trackingCount:'移动物体数',trackingTargets:'追踪目标数',chainPairs:'任务对数'};const details=Object.entries(c.options||{}).filter(([key])=>key!=='level').map(([key,value])=>key==='observation'&&value===0?'手动结束观察':`${labels[key]||'任务设置'} ${value}`).join('，');return `${modes[r.mode]} · ${c.difficulty==='challenge'?'进阶':'轻松'} · ${{still:'静止',slow:'慢速',normal:'标准'}[c.motion]}${c.numbers?' · 1–'+c.numbers:''}${c.level?' · 第 '+c.level+' 关':''}${c.layout==='compact'?' · 小屏静止布局':''}${details?' · '+details:''}`;}
 function renderHistory(){
  const available=api.games.filter(g=>records.some(r=>r.game===g.id));if(!available.some(g=>g.id===game))game=records[0]?.game||null;
  const all=records.filter(r=>r.game===game),groups=[...new Set(all.map(contextKey))];if(!groups.includes(group))group=groups[0]||null;
  const selected=all.filter(r=>contextKey(r)===group),rows=selected.slice(0,40).reverse(),label=rows.length?contextLabel(rows[0]):'';
  show(`<section class="progress-panel"><span class="eyebrow">给家长 · 回合与曲线</span><h1 tabindex="-1">看看每一轮怎样完成</h1><p>已保存 ${records.length} 个完成回合，包括试玩、正式回合和旅程。这里只回顾游戏过程，不给孩子排名。</p>${records.length?`<div class="record-controls"><label>游戏<select data-progress-field="game">${available.map(g=>`<option value="${g.id}" ${game===g.id?'selected':''}>${g.name}</option>`).join('')}</select></label><label>比较条件<select data-progress-field="group">${groups.map((key,i)=>`<option value="${i}" ${group===key?'selected':''}>${esc(contextLabel(all.find(r=>contextKey(r)===key)))}</option>`).join('')}</select></label><label>曲线指标<select data-progress-field="metric">${Object.entries(metrics).map(([key,m])=>`<option value="${key}" ${metric===key?'selected':''}>${m.name}</option>`).join('')}</select></label></div><div class="record-chart-panel"><h2>${metrics[metric].name} · 最近 ${rows.length} 个同条件回合</h2>${group==='unknown'?'<div class="chart-empty">这些记录的条件不完整，或中途改变了动态；保留明细，不与其他回合连成曲线。</div>':chartSVG(rows,metric)}<p class="micro">一个点代表一个完成回合，横轴按完成先后排列。${rows.length<2?'至少两次相同条件的完成记录，才会连成线。':''}快慢、帮助和重试会受当天状态与题目变化影响，不能据此判断训练效果。</p></div><details class="record-details" open><summary>本组回合明细 · ${selected.length} 次（展示最近 40 次）</summary><div class="record-table-wrap"><table class="record-table"><thead><tr><th>完成时间</th><th>重试</th><th>帮助</th><th>有效时间</th><th>有效操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(new Date(r.date).toLocaleString('zh-CN'))}</td><td>${r.retries}</td><td>${r.hints}</td><td>${r.seconds} 秒</td><td>${r.correct??'未记录'}</td></tr>`).join('')}</tbody></table></div></details><div class="progress-actions"><button class="secondary" data-action="progress-export">导出全部回合 CSV</button><button class="quiet" data-action="progress-clear">清除回合记录</button></div>${clearing?'<div class="record-confirm" role="group" aria-label="确认清除记录"><p>清除这台设备的曲线和回合明细？积分、礼物、探索印章及旅程进度会保留。</p><button class="secondary" data-action="progress-clear-confirm">确认清除</button><button class="quiet" data-action="progress-clear-cancel">保留记录</button></div>':''}`:'<div class="chart-empty">完成一小轮喜欢的游戏后，记录会出现在这里。</div>'}<p class="micro">只比较同一游戏、模式、难度、动态与任务设置；旧记录缺少设置时只保留明细。最多保留最近 ${limit} 个完成回合，可导出备份。暂停时间不计入有效时间；未完成回合不写成绩。记录仅在当前浏览器，不跨设备同步。</p>${!recordsOK?'<p role="status">当前浏览器无法保存新记录，请导出备份；关闭后可能丢失。</p>':''}<p role="status">${downloadMessage}</p></section>`);
 }
 function render(){read();if(screen==='passport')renderPassport();else renderHistory();}
 function open(which){api.enter();active=true;screen=which;clearing=false;downloadMessage='';if(which==='history'){read();game=records[0]?.game||null;group=null;}render();}
 function handle(action){
  if(action==='history'){open('history');return true;}if(action==='passport-open'){open('passport');return true;}
  if(!action.startsWith('progress-'))return false;if(!active)return true;
  if(action==='progress-home'){active=false;api.home();}
  else if(action==='progress-clear'){clearing=true;render();}
  else if(action==='progress-clear-cancel'){clearing=false;render();}
  else if(action==='progress-clear-confirm'&&clearing){records=[];writeRecords();try{localStorage.removeItem('star-team-history');}catch{}clearing=false;render();}
  else if(action==='progress-export'){try{const url=URL.createObjectURL(new Blob([csvRounds(records,names)],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='星际小队-游戏回合-'+localDay()+'.csv';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);downloadMessage='已生成全部回合的 CSV 文件。';}catch{downloadMessage='当前浏览器不能导出，请换支持下载的浏览器。';}render();}
  return true;
 }
 function change(target){const field=target.dataset.progressField;if(!active||screen!=='history'||!field)return false;if(field==='game'&&ids.includes(target.value)){game=target.value;group=null;}else if(field==='metric'&&Object.hasOwn(metrics,target.value))metric=target.value;else if(field==='group'){const keys=[...new Set(records.filter(r=>r.game===game).map(contextKey))];group=keys[Number(target.value)]||null;}render();return true;}
 return {complete,handle,change,passportCard,passportButton,leave:()=>{active=false;},refresh:()=>{if(!active)return false;render();return true;}};
}
